import type { Chapter } from "./types";
import { TUTORIALS, CHAPTER_INTROS } from "./tutorials";

/* PyLand 课程数据 —— 从 HTML 版 COURSES 移植
   内容更新只改这个文件，UI 逻辑不用碰。 */

export const COURSES: Chapter[] = [
{
  id: "ch1", no: "第一章", title: "初识咒语",
  sub: "print · 变量 · input · 数据类型",
  levels: [
  {
    id: "l1", title: "第一句咒语", icon: "🗣️", boss: false,
    desc: "print()：让大陆听见你",
    story: "你踏进 PyLand 的入门村。村长格伦捋着胡子说：“每个代码术士的第一步，都是让大陆听见你的声音。来，念出你的第一句咒语——print。”",
    teach: [
      "print() 是让计算机说话的咒语。括号里放什么，屏幕就显示什么。这个括号和引号都必须是英文半角——中文的（）和「“”」计算机不认。",
      '想显示文字，要给文字加引号：print("你好")。引号里的内容叫「字符串」，空格、标点都会原样保留，显示时引号本身不会出现。',
      '单引号双引号都行：print(\'你好\') 和 print("你好") 效果一样，但必须成对——开头双结尾单会报错。',
      "想显示数字或算式，直接写：print(42) 或 print(3 + 4)——算式会先计算，再把结果显示出来。",
      "四则运算符长这样：+ 加、- 减、* 乘、/ 除。没有 × 和 ÷，乘除用星号和斜杠。乘除还遵循先乘除后加减：print(1 + 2 * 3) 是 7 不是 9。",
      "print() 自带换行：一次 print 显示完，光标自动跳到下一行。两个 print 就是两行，不用自己管换行。",
      "# 后面是注释：写给人看的笔记，计算机直接忽略。可以独占一行，也可以跟在代码后面。好注释是给三个月后的自己看的。",
      "Python 区分大小写：print 是咒语，Print / PRINT 都不认识——会报 NameError。",
      '括号里可以放多个东西，用逗号隔开：print("血量", 100) 会显示「血量 100」——逗号的位置自动变空格。这招比 + 拼接省事，还不会报错。',
      "常见报错长相：SyntaxError 多半是引号/括号没配对，或者用了中文符号；NameError 多半是拼写错了（比如 Print）。",
      "新手心法：报错不可怕。看报错最后一行 + 检查引号括号是不是英文半角，八成的错自己就能修。",
    ],
    tutorial: TUTORIALS.l1,
    questions: [
      { type: "choice", q: "哪句咒语能让屏幕显示「你好，PyLand」？",
        options: ['print("你好，PyLand")', 'Print("你好，PyLand")', 'print(你好，PyLand)', '你好.print("PyLand")'],
        answer: 0,
        explain: "B 的 Print 首字母大写了，Python 不认；C 的文字没加引号，计算机会当成代码名而报错；D 的顺序写反了。print 在前，内容在括号里。" },
      { type: "predict", code: 'print("A")\nprint("B")', q: "运行后屏幕会显示什么？",
        options: ["AB 挤在同一行", "A 和 B 各占一行", "只显示 A", "直接报错"],
        answer: 1,
        explain: "每个 print() 自带一次换行。想挤在同一行需要别的咒语，以后再学。" },
      { type: "blank", q: "补全咒语，让屏幕显示「出发！」", code: '___("出发！")', answer: "print",
        explain: "让计算机说话的咒语是 print，注意全小写。" },
      { type: "judge", q: "print() 每显示一次内容，最后都会自动换行。", answer: true,
        explain: "对，换行是 print 自带的默认行为，不用你操心。" },
      { type: "predict", code: 'print(2 * 3)', q: "运行后屏幕会显示什么？",
        options: ["6", "23", "2 * 3", "报错"],
        answer: 0,
        explain: "乘法用星号 *。print 里的算式先计算再显示，结果是 6。" },
      { type: "choice", q: "下面哪一行是 Python 的注释？",
        options: ["// 这行是注释", "# 这行是注释", "print(注释)", "/* 这行是注释 */"],
        answer: 1,
        explain: "Python 用 # 号写注释。// 和 /* */ 是其他语言的写法。" },
      { type: "predict", code: 'print(3 + 4)', q: "运行后屏幕会显示什么？",
        options: ["3 + 4", "7", "3+4", "报错"],
        answer: 1,
        explain: "print 里的算式会先计算，再把结果 7 显示出来。" },
      { type: "blank", q: "补全引号里的内容，让屏幕显示 hello", code: 'print("___")', answer: "hello",
        explain: "引号里写什么就显示什么。注意 hello 全小写。" },
      { type: "judge", q: 'print("你好") 和 print(\'你好\') 效果完全一样。', answer: true,
        explain: "双引号、单引号都可以包文字，只要成对出现，效果一样。" },
      { type: "code", q: "实操：亲手写开场咒语。第一行注释已给你写好，接着先显示「准备……」，再显示「出发！」",
        starter: "# 冒险开始\n",
        expected: "准备…\n出发！",
        explain: "两个 print 各管一行，顺序反了输出也会反——程序永远从上往下执行。" },
    ],
  },
  {
    id: "l2", title: "魔法容器", icon: "📦", boss: false,
    desc: "变量：贴了标签的箱子",
    story: "铁匠安娜带你走进仓库，里面全是贴着标签的箱子。“变量就是贴了标签的魔法箱子——标签是名字，箱子里装着数据。想要什么，喊标签就行。”",
    teach: [
      "hp = 100 的意思是：把 100 装进名叫 hp 的箱子。= 不是「等于」，是「装进去」（赋值）。念的时候念「装进去」，别念「等于」。",
      "箱子里的东西随时可以换：hp = 100 之后再写 hp = 80，箱子里就是 80 了——永远以最后一次为准。",
      '想看箱子里装了什么：print(hp)。注意——print(hp) 显示 100，而 print("hp") 显示 hp 这两个字母。带不带引号，天差地别。',
      "hp = hp - 30 的意思是：把箱子里的数取出来减 30，再放回箱子。等号右边先算完，才装回去。",
      'b = a 是「抄一份」：把 a 箱子里的值抄进 b。之后 a 再怎么变，跟 b 没关系了——抄的是值，不是箱子本身。',
      "变量名规则：只能用字母、数字、下划线；不能以数字开头；不能用 print、if、class 这类被咒语系统占用的关键字。",
      "起名习惯：全小写 + 下划线，比如 max_hp、player_name、total_damage。看名字就知道装什么，是最重要的起名原则——别起 a、b、xxx 这种名字。",
      "这些名字都不合法：2level（数字开头）、my-name（横线会被当成减号）、my name（不能有空格）。",
      "变量名区分大小写：HP、hp、Hp 是三个不同的箱子。别自己坑自己，统一用小写。",
      '箱子什么都能装：数字、文字、以后学的列表字典都行。x = "Corrin" 和 x = 42 都是合法操作。',
      "变量必须先造再用：print(level) 之前从没写过 level = …，会报 NameError——意思是「不认识这个名字」。",
      "==（两个等号连着）才是「等于」的判断。现在先记住长相别搞混，第二章天天用。",
    ],
    tutorial: TUTORIALS.l2,
    questions: [
      { type: "choice", q: '执行 name = "Corrin" 之后，name 里装的是什么？',
        options: ["name 这四个字母", "Corrin 这串文字", "Corrin 外面还带引号", "会报错"],
        answer: 1,
        explain: "引号只是「这是文字」的标记，装进箱子时引号会被脱掉，箱子里是 Corrin。" },
      { type: "predict", code: "x = 5\nx = 8\nprint(x)", q: "运行后屏幕会显示什么？",
        options: ["5", "8", "58", "报错"], answer: 1,
        explain: "后面一次赋值会覆盖前面。x 先装 5，再装 8，打开箱子看到的就是 8。" },
      { type: "choice", q: "哪句咒语能创建名叫 coin 的箱子，并装进 50？",
        options: ["coin == 50", "coin = 50", "50 = coin", "coin: 50"], answer: 1,
        explain: "赋值用单个等号 =，箱子名在左、值在右。== 是「比较是否相等」，不是装东西。" },
      { type: "judge", q: "变量一旦赋值，里面的值就再也不能更改了。", answer: false,
        explain: "变量箱子的核心特性就是随时可换。重新赋值即覆盖。" },
      { type: "predict", code: "a = 10\nb = a\na = 20\nprint(b)", q: "运行后屏幕会显示什么？",
        options: ["20", "10", "1020", "报错"], answer: 1,
        explain: "b = a 是把 a 箱子里的 10 抄一份装进 b。之后 a 换成 20，跟 b 没关系了。" },
      { type: "choice", q: "下面哪个是合法的变量名？",
        options: ["2level", "my-name", "level_2", "print"], answer: 2,
        explain: "A 数字开头不行；B 里的横线会被当成减号；D 的 print 是关键字，被咒语系统占用了。下划线是唯一能用的符号。" },
      { type: "predict", code: 'spell = "魔法"\nprint(spell)', q: "运行后屏幕会显示什么？",
        options: ["spell", "魔法", "\"魔法\"", "报错"], answer: 1,
        explain: "print(spell) 打开的是箱子，显示箱中内容；想显示 spell 这串字母得写 print(\"spell\")。" },
      { type: "judge", q: "hp = 100 里的 = 读作「等于」，意思是两边一样。", answer: false,
        explain: "= 是赋值（装进去），不是等于。想知道两边是否相等要用 ==。" },
      { type: "blank", q: "把 99 装进名叫 mp 的箱子（补全符号）", code: "mp ___ 99", answer: "=",
        explain: "装进去的符号是等号 =，念作「赋值」，不是「等于」。" },
      { type: "blank", q: "创建名叫 hp 的箱子，装进 100（补全变量名）", code: "___ = 100", answer: "hp",
        explain: "变量名在等号左边。取名要合法：不用数字开头、不用横线。" },
      { type: "code", q: "实操：造一个名叫 level 的箱子装 1，先显示箱子里的值，再把箱中数加 1，最后显示「升级！」（两行输出）",
        starter: "",
        expected: "1\n升级！",
        explain: 'level = 1 造箱子 → print(level) 显示 1 → level = level + 1 → print("升级！")。变量没造就使用会报错。' },
      { type: "code", q: "实操：造一个名叫 x 的箱子装 5，把 x 加上 3 放回去，先显示 x，再显示「完成」（两行输出）",
        starter: "",
        expected: "8\n完成",
        explain: 'x = x + 3 是「取出、加 3、放回」，所以 x 变成 8，再 print(x)、print("完成")。' },
    ],
  },
  {
    id: "l3", title: "与大陆对话", icon: "👂", boss: false,
    desc: "input()：程序竖起耳朵",
    story: "旅店老板娘米娅能记住每位旅人的名字。“input() 就是让程序竖起耳朵——它先问你一句话，然后耐心等你输入，再把你的话装进变量箱子里。”",
    teach: [
      'name = input("你叫什么？") → 先显示提示语「你叫什么？」，然后程序停住等你输入，按回车后输入内容装进 name。',
      "input() 括号里也可以留空，但用户会一脸懵不知道要输什么——养成写提示语的习惯。",
      "大坑预警：input() 收到的永远是文字（字符串）！哪怕你输入 18，装进箱子的也是 \“18\” 这串文字，不是数字。",
      '文字数字不分清会出事："3" * 2 得到 33（重复两遍），不是 6；"3" + 1 直接报错。',
      '转换咒语三件套：int("18") 变整数 18、float("1.8") 变小数、str(18) 整数变文字。转的方向想清楚再转。',
      'int() 只认「长得像整数」的文字：int("18") 没问题，但 int("abc") 或 int("3.5") 会报 ValueError——它不猜，转不动就罢工。',
      '常见组合技：age = int(input("年龄？")) —— 一行完成「收话 + 转数字」。读代码从里往外：先 input 收到文字，再 int 转成数字。',
      "提示语只显示一次；你输入的内容不会自动显示在屏幕上——想回显得自己 print。",
      "交互程序的固定套路：input 收集 → int/float 转类型 → 变量做计算 → print 输出结果。四步走完就是一个小程序。",
      "记忆口诀：input 进来的都当文字。要用它算数，先过 int() / float() 这道门。",
    ],
    tutorial: TUTORIALS.l3,
    questions: [
      { type: "choice", q: '执行 age = input("请输入年龄")，用户输入了 18。age 里装的是什么？',
        options: ["整数 18", "文字 \"18\"", "小数 18.0", "报错"], answer: 1,
        explain: "input 收到的永远是字符串。它是文字「18」，不是数字 18——这就是新手最常踩的坑。" },
      { type: "predict", code: 'n = input("输入数字")\nprint(n * 2)\n（用户输入了 3）', q: "运行后屏幕会显示什么？",
        options: ["6", "33", "3", "报错"], answer: 1,
        explain: 'n 是文字 "3"。文字乘 2 不是算数学，是「重复两遍」→ 33。想得到 6 得先 int(n)。' },
      { type: "judge", q: 'input("你叫什么？") 里的提示语会显示在屏幕上。', answer: true,
        explain: "括号里的文字就是给用户看的提示：先显示提示，再等待输入。" },
      { type: "judge", q: "input() 收到的内容可以直接和数字相加。", answer: false,
        explain: '文字和数字不能直接相加，"3" + 1 会报错。先用 int() 转换。' },
      { type: "predict", code: 'n = int(input("输入数字"))\nprint(n * 2)\n（用户输入了 4）', q: "运行后屏幕会显示什么？",
        options: ["8", "44", "4", "报错"], answer: 0,
        explain: "int() 把输入的文字 4 转成数字 4，4 × 2 = 8。对比上一题：转不转，结果天差地别。" },
      { type: "choice", q: "想让输入的数字做加法，哪种写法是对的？",
        options: ["n = input() + 1", "n = int(input()) + 1", "n = input(int())", "int = n + 1"], answer: 1,
        explain: "先把输入转成整数，再做加法。A 是文字加数字，报错；C 顺序写反；D 把变量名写成 int 了。" },
      { type: "blank", q: "补全咒语：把用户输入直接转成整数装进 age", code: 'age = ___(input("年龄"))', answer: "int",
        explain: "int() 是把文字转整数的咒语。转小数用 float()。" },
      { type: "blank", q: "补全咒语：把用户输入的体重转成小数装进 w", code: 'w = ___(input("体重"))', answer: "float",
        explain: "float() 把文字转成小数。体重身高这类带小数点的数用它。" },
      { type: "predict", code: 'name = input("名字")\nprint("你好，" + name)\n（用户输入了 Corrin）', q: "运行后屏幕会显示什么？",
        options: ["你好，Corrin", "你好，+ name", "你好，name", "报错"], answer: 0,
        explain: "文字 + 文字 = 拼接。引号里的原样显示，变量打开箱子取值。" },
      { type: "code", q: "实操：age 箱子已经造好（见起始代码）。显示明年的年龄（一行输出）",
        starter: "age = 18\n",
        expected: "19",
        explain: "print(age + 1) 直接算完显示。也可以先 age = age + 1 再 print(age)，两种都对。" },
    ],
  },
  {
    id: "l4", title: "四系元素", icon: "💎", boss: false,
    desc: "数据类型：万物归四系",
    story: "元素神殿里悬浮着四块水晶，祭司说：“PyLand 万物皆属四系——文字 str、整数 int、小数 float、真伪 bool。分不清元素系别，咒语就会失控。”",
    teach: [
      'str 字符串：被引号包裹的文字。"你好"、\'a\'、"18" 都是——只要带引号，哪怕内容是数字，它也是文字。',
      "int 整数：42、-7、0。不带小数点的完整数。",
      "float 浮点数：带小数点的数，3.14、-0.5，甚至 3.0（小数部分是 0 也算 float）。",
      "bool 布尔：只有 True 和 False 两个值（首字母必须大写），表示真和假——第二章做判断时的主角。",
      "type(x) 是验明元素系的咒语：type(42) → <class 'int'>，type(\“42\”) → <class 'str'>。拿不准就问它。",
      "一眼分辨技巧：带引号全是 str；带小数点是 float；True/False 是 bool；光秃秃的整数才是 int。",
      '转换咒语：int("42") 文字变整数、str(42) 整数变文字、float(3) 变 3.0。int(3.9) 是 3——直接砍掉小数（截断），不是四舍五入。',
      "想要四舍五入用 round()：round(3.5) → 4，round(3.4) → 3。",
      '文字 + 文字 = 拼接："Py" + "Land" → PyLand，中间不会自动加空格。文字 + 数字 = 直接报错，Python 不会自作主张帮你转。',
      '文字 * 数字 = 重复："ha" * 3 → hahaha。这是字符串专属玩法（你已经在 input 关见过 "3" * 2 = 33 了）。',
      "除法 / 的结果永远是 float：10 / 2 是 5.0 不是 5。想要整数结果用整除 //：10 // 2 → 5，7 // 2 → 3（砍掉余数）。",
      "Python 没有 double 这个类型（那是 C / Java 的叫法），小数统一叫 float。",
    ],
    tutorial: TUTORIALS.l4,
    questions: [
      { type: "choice", q: "3.14 属于哪一系元素？",
        options: ["int 整数", "float 浮点数", "str 字符串", "bool 布尔"], answer: 1,
        explain: "带小数点的数就是 float。哪怕 3.0 也是 float 而不是 int。" },
      { type: "predict", code: "print(int(3.9))", q: "运行后屏幕会显示什么？",
        options: ["4", "3", "3.9", "报错"], answer: 1,
        explain: "int() 转换是直接砍掉小数部分（截断），不是四舍五入。想要四舍五入要用 round()。" },
      { type: "judge", q: '"18" 和 18 是一样的东西。', answer: false,
        explain: '"18" 是文字（str），18 是整数（int）。文字不能做数学运算，这是两码事。' },
      { type: "predict", code: 'print("Py" + "Land")', q: "运行后屏幕会显示什么？",
        options: ["PyLand", "Py Land", "Py\nLand", "报错"], answer: 0,
        explain: "文字 + 文字 = 首尾拼接。中间不会自动加空格。" },
      { type: "judge", q: "3.0 是 float 类型，不是 int。", answer: true,
        explain: "只要带小数点，哪怕小数部分是 0，也是 float。" },
      { type: "choice", q: "type(True) 会返回什么？",
        options: ["<class 'bool'>", "<class 'str'>", "<class 'int'>", "报错"], answer: 0,
        explain: "True 和 False 是布尔值。注意首字母大写——true 是错的写法。" },
      { type: "predict", code: 'print("Py" + 2)', q: "运行后屏幕会显示什么？",
        options: ["Py2", "2Py", "报错", "Py"], answer: 2,
        explain: "文字 + 数字会报错！Python 不自动帮你转类型。想拼接要写 \"Py\" + str(2)。" },
      { type: "predict", code: "print(int(7 / 2))", q: "运行后屏幕会显示什么？",
        options: ["3", "3.5", "4", "报错"], answer: 0,
        explain: "7 / 2 = 3.5，int() 再砍掉小数 → 3。除法结果永远是 float，想整除可以用 7 // 2。" },
      { type: "blank", q: "补全咒语：把整数 42 变成文字 \"42\"", code: 'text = ___(42)', answer: "str",
        explain: "str() 是万物变文字的咒语。" },
      { type: "choice", q: "下面哪个值是 bool 类型？",
        options: ['"True"', 'true', 'True', '1'], answer: 2,
        explain: 'A 是文字（有引号）；B 首字母小写不合法；D 是整数。只有 True 是布尔。' },
      { type: "code", q: "实操：用 str() 把整数 42 变成文字，和「生命值：」拼接后显示（一行输出）",
        starter: "",
        expected: "生命值：42",
        explain: 'print("生命值：" + str(42))。文字 + 整数会报错，必须先 str() 转换再拼接。' },
      { type: "blank", q: "补全咒语：把文字 \"42\" 转成数字，让屏幕显示 50", code: 'print(___("42") + 8)', answer: "int",
        explain: 'int("42") 把文字转成整数 42，42 + 8 = 50。不转换的话文字加数字直接报错。' },
    ],
  },
  {
    id: "l5", title: "Boss 战 · 史莱姆王", icon: "👑", boss: true,
    desc: "第一章综合试炼",
    story: "村口的史莱姆王拦住了去路，它浑身果冻般的身体里封印着第一章的所有咒语。“答对我全部的问题，我就认你做 PyLand 的见习代码术士。答错……也没事，你可以重试，但我可要嘲笑你了。”",
    teach: [
      "Boss 战大部分没有新知识——全是你学过的：print、变量、input、数据类型。",
      "新增「实操编程」题：你写的代码会被真的 Python 引擎运行，输出和期望一模一样才算过。报错不扣分随便试，输出错了才计一次失误。",
      "运算全家桶（今天多认识三个）：+ - * / 老四样；// 整除（7 // 2 = 3）；% 取余数（7 % 2 = 1）；** 乘方（2 ** 3 = 8）。",
      "复习清单①print 三要素：全小写、英文括号、文字加引号。",
      "复习清单②变量：先造再用；起名全小写加下划线；b = a 抄的是值。",
      "复习清单③input 进来全是文字，要算数先 int() / float()。",
      "复习清单④类型：带引号是 str，带小数点是 float，True/False 是 bool；拿不准 type() 问。",
      "稳住，先想清楚每行代码「谁先谁后、箱子里装的是什么类型」，再作答。",
      "全部首答答对 = 3星 + 额外 XP。失误了也能过，但星星会少。",
    ],
    tutorial: TUTORIALS.l5,
    questions: [
      { type: "choice", q: "让屏幕显示「战斗开始」，哪句是对的？",
        options: ['print("战斗开始")', 'Print("战斗开始")', 'print(战斗开始)', '"战斗开始".print()'], answer: 0,
        explain: "老规矩：print 全小写、文字加引号、print 在前。" },
      { type: "predict", code: "hp = 50\nhp = hp - 20\nprint(hp)", q: "运行后屏幕会显示什么？",
        options: ["50", "20", "30", "报错"], answer: 2,
        explain: "hp 先装 50，再自减 20 变 30。hp = hp - 20 是「取出-20-放回」。" },
      { type: "predict", code: "print(10 / 2)", q: "运行后屏幕会显示什么？",
        options: ["5", "5.0", "2", "报错"], answer: 1,
        explain: "Python 的除号 / 结果永远是 float。想要整数结果用 // ：10 // 2 才是 5。" },
      { type: "choice", q: "下面哪个「元素系别」在 Python 里根本不存在？",
        options: ["str", "int", "float", "double"], answer: 3,
        explain: "double 是 C / Java 里的类型，Python 没有。Python 的小数叫 float。" },
      { type: "predict", code: 'a = "10"\nb = 3\nprint(a * b)', q: "运行后屏幕会显示什么？",
        options: ["30", "101010", "103", "报错"], answer: 1,
        explain: 'a 是文字 "10"，文字 × 3 = 重复三遍 → 101010。想算 30 要 int(a) * b。' },
      { type: "blank", q: "补全咒语：显示变量 power 箱子里的值", code: "___(power)", answer: "print",
        explain: "print(power) 不加引号——加引号就变成显示 power 这串字母了。" },
      { type: "judge", q: "input() 返回的内容可以直接和数字相加。", answer: false,
        explain: "input 永远返回字符串。先 int() 转换才能做数学。" },
      { type: "judge", q: "10 // 3 的结果是 3.3333……", answer: false,
        explain: "// 是整除（只取整数部分）：10 // 3 = 3。想得到 3.333… 用 / 。" },
      { type: "predict", code: 'hp = 100\nmp = "50"\nprint(hp - int(mp))', q: "运行后屏幕会显示什么？",
        options: ["50", "150", "10050", "报错"], answer: 0,
        explain: 'int("50") 先把文字转成 50，100 - 50 = 50。不转换直接相减会报错。' },
      { type: "judge", q: 'print("2" + "3") 会显示 23。', answer: true,
        explain: '文字 + 文字是拼接不是加法："2" + "3" = "23"。想算 5 要先转成数字。' },
      { type: "code", q: "实操：name 箱子已经造好。显示「你好，Corrin」（一行输出，逗号用中文逗号）",
        starter: 'name = "Corrin"\n',
        expected: "你好，Corrin",
        explain: 'print("你好，" + name)——引号里的原样显示，name 开箱取值，+ 把两段文字拼起来。' },
      { type: "blank", q: "补全咒语：把文字 \"999\" 转成整数装进 gold", code: 'gold = ___("999")', answer: "int",
        explain: "金币数量是整数，用 int() 转换。练到第三次，形成肌肉记忆！" },
      { type: "choice", q: "下面哪个变量名是合法的？",
        options: ["9life", "life-value", "life_value", "class"], answer: 2,
        explain: "数字不能开头；横线会被当减号；class 是关键字。下划线永远安全。" },
      { type: "predict", code: "print(type(3))", q: "运行后屏幕会显示什么？",
        options: ["<class 'int'>", "<class 'float'>", "<class 'str'>", "3"], answer: 0,
        explain: "3 是整数，type() 验明正身返回 <class 'int'>。" },
      { type: "code", q: "实操：造 dmg1 装 30、dmg2 装 45，显示两者之和（一行输出）",
        starter: "# 计算总伤害\n",
        expected: "75",
        explain: "dmg1 = 30、dmg2 = 45，然后 print(dmg1 + dmg2)。也可以先 total = dmg1 + dmg2 再 print(total)。" },
    ],
  },
  ],
},
{
  id: "ch2", no: "第二章", title: "岔路抉择", sub: "if / else / 循环",
  levels: [
  {
    id: "l6", title: "岔路口的守卫", icon: "🗿", boss: false,
    desc: "if / else：让程序学会做选择",
    story: "穿过入门村，你来到一座石桥前。桥头立着一尊石像守卫，眼中亮起蓝光：「想过桥，先证明你能做出正确的抉择。if，就是抉择的咒语。」",
    teach: [
      "if 是「如果」：if 后面跟一个条件，条件成立（True）才执行下面的缩进块。写法：if hp > 50: ——注意行尾必须有个冒号:（英文半角）。",
      "缩进是 Python 的灵魂：if 下面缩进 4 个空格的行，都属于这个 if 管的范围。缩进消失，if 的管辖就结束了。",
      "比较运算符六兄弟：== 等于、!= 不等于、> 大于、< 小于、>= 大于等于、<= 小于等于。比较的结果只有两种：True 或 False。",
      "== 和 = 完全不同：== 是问「相等吗」（比较），= 是「装进去」（赋值）。把 if x == 5 写成 if x = 5 会直接报 SyntaxError。",
      "else 是「否则」：if 条件不成立时走 else。if 和 else 二选一必走其一，像岔路口的两条路。",
      "条件的本质是布尔值：bool 类型只有 True 和 False 两个值。注意首字母大写，true/false 是小写会报 NameError。",
      "if 可以单独存在（不写 else），条件不成立就整段跳过，程序继续往下走。",
      "字符串也能比较：'a' == 'a' 是 True。但 '5' == 5 是 False——带引号的是文字，不带的是数字，类型不同永不相等。",
      "缩进必须整整齐齐：同一个 if 块里的行缩进要完全一样（都是 4 空格或都是 2 空格）。混用 Tab 和空格会报 IndentationError。",
      "冒号后换行才缩进：if hp > 50: print('安全') 这种单行写法虽然合法，但新手期统一写成两行——冒号结尾、换行缩进，格式最清晰。",
      "常见报错：SyntaxError: invalid syntax 多半是忘了冒号；IndentationError: expected an indented block 是冒号后面忘了缩进。",
    ],
    tutorial: TUTORIALS.l6,
    questions: [
      { type: "choice", q: "下面哪句代码能让程序在 hp 小于 30 时显示「危险」？",
        options: ["if hp < 30:\n    print('危险')", "if hp < 30\n    print('危险')", "if (hp < 30) { print('危险') }", "if hp < 30: then print('危险')"],
        answer: 0,
        explain: "Python 的 if 需要：条件 + 冒号 + 换行缩进。B 少了冒号；C 是其他语言的写法；D 的 then 是别的语言的关键字，Python 不用。" },
      { type: "predict", code: "hp = 100\nif hp > 50:\n    print('安全')\nprint('检查完毕')", q: "运行后屏幕会显示什么？",
        options: ["安全\n检查完毕", "只显示 安全", "只显示 检查完毕", "什么都不显示"],
        answer: 0,
        explain: "hp > 50 成立，先显示「安全」；最后一行没缩进，不属于 if 块，无论如何都会执行。" },
      { type: "judge", q: "if x = 5: 是判断 x 是否等于 5 的正确写法。", answer: false,
        explain: "= 是赋值，判断相等要用两个等号 ==。写成 = 会直接报 SyntaxError。" },
      { type: "blank", q: "补全咒语：如果 hp 不等于 0 就继续战斗（补全比较符号）", code: "if hp ___ 0:\n    print('继续战斗')", answer: "!=",
        explain: "!= 是「不等于」。如果想在 hp 不为 0 时触发，条件就是 hp != 0。" },
      { type: "predict", code: "age = 15\nif age >= 18:\n    print('成年人')\nelse:\n    print('未成年人')", q: "运行后屏幕会显示什么？",
        options: ["成年人", "未成年人", "成年人和未成年人都显示", "报错"],
        answer: 1,
        explain: "age >= 18 不成立（15 < 18），所以走 else 分支。if 和 else 必走其一，绝不都走。" },
      { type: "choice", q: "执行 print(10 != 3) 会显示什么？",
        options: ["True", "False", "10 != 3", "报错"],
        answer: 0,
        explain: "10 不等于 3，这个判断是真的，所以结果是 True。比较运算的结果就是布尔值。" },
      { type: "predict", code: "mp = 0\nif mp > 10:\n    print('释放火球')\nprint('回合结束')", q: "运行后屏幕会显示什么？",
        options: ["释放火球\n回合结束", "回合结束", "释放火球", "什么都不显示"],
        answer: 1,
        explain: "mp > 10 不成立，if 块整段跳过；「回合结束」不在缩进里，照常执行。" },
      { type: "judge", q: "if 块必须配一个 else，否则会报错。", answer: false,
        explain: "else 是可选的。只有 if 也完全合法——条件不成立就跳过，什么都不做。" },
      { type: "predict", code: "print('5' == 5)", q: "运行后屏幕会显示什么？",
        options: ["True", "False", "报错", "5"],
        answer: 1,
        explain: "带引号的 '5' 是文字，不带引号的 5 是数字。类型不同，永不相等——结果是 False。" },
      { type: "code", q: "实操：score 装着 85（已给你写好）。如果 score 大于等于 60，显示「及格」，否则显示「不及格」（一行输出）",
        starter: "score = 85\n",
        expected: "及格",
        explain: "score = 85 已给出，你只需要写 if score >= 60:（缩进）print('及格') + else:（缩进）print('不及格')。85 >= 60 成立，所以显示及格。" },
      { type: "code", q: "实操：a 装 7、b 装 12（已给你写好）。显示 a 和 b 中较大的那个数（一行输出，就一个数字）",
        starter: "a = 7\nb = 12\n",
        expected: "12",
        explain: "if a > b: 显示 a，else: 显示 b。7 < 12，所以走 else 显示 12。" },
      { type: "code", q: "实操：hp 装着 35（已给你写好）。如果 hp 小于等于 30，显示「撤退」，否则显示「继续前进」（一行输出）",
        starter: "hp = 35\n",
        expected: "继续前进",
        explain: "35 <= 30 不成立，走 else 分支。注意 <= 是「小于等于」，别写成 =<。" },
    ],
  },
  {
    id: "l7", title: "三岔路口", icon: "🔀", boss: false,
    desc: "elif：更多岔路一次选完",
    story: "石桥之后是一条三岔路，路口的指路石上刻着三行字。守卫的声音从远处传来：「两个岔口用 if 和 else，三个以上，你需要 elif。」",
    teach: [
      "elif 是「否则如果」：else if 的缩写。当 if 的条件不成立时，接着检查 elif 的条件。",
      "if / elif / else 是一条链：从上往下逐个检查，哪个条件先成立就走哪条岔路，走完就离开整条链——后面的条件不再看。",
      "else 放在最后兜底：前面全不成立才走 else。else 后面不跟条件，只跟冒号。",
      "elif 可以有任意多个：if 一个、elif 零到多个、else 最多一个（可省略）。",
      "顺序很重要：把宽的条件放前面会「截胡」。比如先写 if score >= 60 再写 elif score >= 90，那 95 分也只会走第一个分支——>= 90 永远轮不到。",
      "条件链只会走一条路：哪怕后面还有成立的条件也不看。这跟多个独立 if 的区别——独立的 if 各自判断互不干扰。",
      "嵌套 if：if 里面还能再放 if，靠缩进区分层级。但嵌套太深可读性差，能用 elif 拆开就拆开。",
      "常见坑：elif 写成 else if（Python 不认两个词）；elif 后面忘了条件直接冒号（那是 else 的写法）。",
      "分数分级是经典应用：90+ 优秀、80+ 良好、60+ 及格、其余不及格——从高到低排，每档只写一个条件。",
    ],
    tutorial: TUTORIALS.l7,
    questions: [
      { type: "choice", q: "score 是 75。下面代码显示什么？\nif score >= 90:\n    print('优秀')\nelif score >= 60:\n    print('及格')\nelse:\n    print('不及格')",
        options: ["优秀", "及格", "不及格", "及格和不及格都显示"],
        answer: 1,
        explain: "75 >= 90 不成立，检查下一个：75 >= 60 成立，走这条。整条链走一次就结束，else 不再看了。" },
      { type: "predict", code: "x = 100\nif x > 200:\n    print('A')\nelif x > 50:\n    print('B')\nelif x > 10:\n    print('C')", q: "运行后屏幕会显示什么？",
        options: ["B", "C", "B 和 C", "什么都不显示"],
        answer: 0,
        explain: "条件链从上往下：x > 200 不成立；x > 50 成立，显示 B 就离开整条链。C 的条件虽然也成立，但已经轮不到它了。" },
      { type: "judge", q: "if / elif / else 条件链中，最多只会执行其中一个分支。", answer: true,
        explain: "对，这是条件链的核心：从上往下找到第一个成立的就走，走完立刻离开。" },
      { type: "blank", q: "补全关键字：score 等于 100 时显示「满分」的结构（补全第二个分支的关键字）", code: "if score == 100:\n    print('满分')\n___ score >= 60:\n    print('及格')", answer: "elif",
        explain: "「否则如果」是 elif，一个词，中间不能有空格。" },
      { type: "choice", q: "下面哪个写法是合法的？",
        options: ["if x > 0:\n    print('正')\nelse if x < 0:\n    print('负')", "if x > 0:\n    print('正')\nelif x < 0:\n    print('负')", "if x > 0:\n    print('正')\nelif:\n    print('负')", "if x > 0:\n    print('正')\nelse x < 0:\n    print('负')"],
        answer: 1,
        explain: "A 的 else if 是两个词，Python 不认；C 的 elif 后面必须有条件；D 的 else 后面不能跟条件。" },
      { type: "predict", code: "level = 3\nif level >= 5:\n    print('大师')\nelif level >= 2:\n    print('学徒')\nelse:\n    print('新手')", q: "运行后屏幕会显示什么？",
        options: ["大师", "学徒", "新手", "学徒和新手"],
        answer: 1,
        explain: "3 >= 5 不成立；3 >= 2 成立，显示「学徒」后离开整条链。" },
      { type: "judge", q: "elif 必须写在 else 后面，作为整条链的最后一个分支。", answer: false,
        explain: "恰恰相反——elif 在 else 前面，else 才是链的最后兜底。elif 写在 else 后面会报 SyntaxError。" },
      { type: "predict", code: "hp = 0\nif hp > 0:\n    print('战斗')\nelif hp == 0:\n    print('倒下')\nelse:\n    print('异常')", q: "运行后屏幕会显示什么？",
        options: ["战斗", "倒下", "异常", "什么都不显示"],
        answer: 1,
        explain: "hp > 0 不成立；hp == 0 成立，显示「倒下」。else 只在前面全不成立时才走。" },
      { type: "code", q: "实操：score 装着 92（已给你写好）。按分数分级——大于等于 90 显示「优秀」，大于等于 60 显示「及格」，否则显示「不及格」（一行输出）",
        starter: "score = 92\n",
        expected: "优秀",
        explain: "条件从高到低排：先 if score >= 90（92 命中，显示优秀），再 elif score >= 60，最后 else 兜底。" },
      { type: "code", q: "实操：num 装着 7（已给你写好）。判断奇偶——能被 2 整除显示「偶数」，否则显示「奇数」。提示：整除判断用余数运算符 %（一行输出）",
        starter: "num = 7\n",
        expected: "奇数",
        explain: "if num % 2 == 0: 显示偶数，else 显示奇数。7 % 2 是 1（余 1），不等于 0，所以走 else。% 是取余数运算符，判断奇偶全靠它。" },
      { type: "code", q: "实操：gold 装着 150（已给你写好）。按钱数给武器——大于等于 200 显示「传说武器」，大于等于 100 显示「精良武器」，否则显示「木棍」（一行输出）",
        starter: "gold = 150\n",
        expected: "精良武器",
        explain: "if gold >= 200 → elif gold >= 100 → else。150 不到 200 但过了 100，走第二个分支。" },
    ],
  },
  {
    id: "l8", title: "逻辑之门", icon: "🚪", boss: false,
    desc: "and / or / not：组合条件",
    story: "山道尽头并排立着三扇石门，门上刻着奇怪的符号：and、or、not。守卫的声音再次响起：「有的门要两把钥匙同开，有的门一把就够。学会组合条件，三扇门任你通行。」",
    teach: [
      "and 是「并且」：两边都成立才是 True。hp > 0 and mp > 0 ——血量和蓝量都在线才放技能，缺一个都不行。",
      "or 是「或者」：两边至少一个成立就是 True。周五 or 周末就能休息——只要占一天就成立。",
      "not 是「取反」：True 变 False，False 变 True。not hp > 0 等价于 hp <= 0，读作「血量不大于 0」。",
      "优先级口诀：not > and > or。不确定就加括号，括号最清晰还不容易错。",
      "组合出来的还是布尔值：print(3 > 1 and 2 > 1) 会显示 True。and/or 运算的结果照样能用 print 显示、能当 if 的条件。",
      "常见坑——数学写法：想表达「0 到 100 之间」不能写 0 <= score <= 100 之外的 0 < score < 100 其实 Python 支持，但别写成 score > 0 and < 100（后半截缺变量，直接报错）。",
      "Python 彩蛋：链式比较 0 <= score <= 100 是合法的，等价于 0 <= score and score <= 100。数学课的写法直接能用。",
      "and 短路：左边是 False 时右边直接不看了（已经注定 False）。or 短路：左边是 True 时右边也不看。新手知道有这回事就行。",
      "多个条件组合的读法：age >= 18 and age <= 65 读作「18 到 65 岁」。写代码时把长条件拆开来读，逻辑立刻清晰。",
    ],
    tutorial: TUTORIALS.l8,
    questions: [
      { type: "choice", q: "print(True and False) 会显示什么？",
        options: ["True", "False", "报错", "True and False"],
        answer: 1,
        explain: "and 要求两边都是 True 结果才是 True。有一边是 False，结果就是 False。" },
      { type: "predict", code: "print(3 > 1 or 2 > 5)", q: "运行后屏幕会显示什么？",
        options: ["True", "False", "报错", "3"],
        answer: 0,
        explain: "or 只要求一边成立。3 > 1 是 True，够了——右边 2 > 5 是 False 也不影响结果。" },
      { type: "judge", q: "not False 的结果是 True。", answer: true,
        explain: "not 就是取反：True 变 False，False 变 True。" },
      { type: "predict", code: "hp = 50\nmp = 0\nif hp > 0 and mp > 0:\n    print('释放技能')\nelse:\n    print('蓝量不足')", q: "运行后屏幕会显示什么？",
        options: ["释放技能", "蓝量不足", "两个都显示", "报错"],
        answer: 1,
        explain: "hp > 0 是 True，但 mp > 0 是 False——and 两边有一个 False，整体就是 False，走 else。" },
      { type: "blank", q: "补全关键字：年龄在 18 到 65 之间才算「适龄」（补全逻辑符号）", code: "if age >= 18 ___ age <= 65:\n    print('适龄')", answer: "and",
        explain: "「18 到 65 之间」是两个条件同时成立，用 and 连接。" },
      { type: "choice", q: "今天 is_holiday 是 False、is_weekend 是 True。哪个条件能让你休息（结果为 True）？",
        options: ["is_holiday and is_weekend", "is_holiday or is_weekend", "not is_weekend", "is_holiday and not is_weekend"],
        answer: 1,
        explain: "or 只要一边是真就是真。A 两边都得真（不满足）；C 取反变成 False；D 要求假期真且周末假（不满足）。" },
      { type: "predict", code: "print(not 5 > 3)", q: "运行后屏幕会显示什么？",
        options: ["True", "False", "报错", "5"],
        answer: 1,
        explain: "先算 5 > 3 得 True，not 取反变成 False。not 只对它右边那一小段取反。" },
      { type: "judge", q: "print(1 > 2 and 3 > 2) 的结果是 True，因为右边成立。", answer: false,
        explain: "and 是「都成立才成立」。左边 1 > 2 已经是 False，整体必是 False，右边再真也没用。" },
      { type: "code", q: "实操：hp 装 80、mp 装 20（已给你写好）。如果 hp 大于 50 并且 mp 大于 10，显示「状态良好」，否则显示「需要恢复」（一行输出）",
        starter: "hp = 80\nmp = 20\n",
        expected: "状态良好",
        explain: "if hp > 50 and mp > 10: ——80 > 50 是 True，20 > 10 也是 True，and 两边都真，走 if 分支。" },
      { type: "code", q: "实操：ticket 装 False、vip 装 True（已给你写好）。有票或者有 VIP 任一满足就显示「欢迎入场」，否则显示「请购票」（一行输出）",
        starter: "ticket = False\nvip = True\n",
        expected: "欢迎入场",
        explain: "if ticket or vip: ——ticket 是 False 但 vip 是 True，or 一边真整体就是 True。" },
      { type: "code", q: "实操：level 装 5（已给你写好）。level 大于等于 1 并且 level 小于等于 10 时显示「新手区」，否则显示「进阶区」（一行输出）",
        starter: "level = 5\n",
        expected: "新手区",
        explain: "if level >= 1 and level <= 10: ——两边都成立。Python 也支持连写 1 <= level <= 10，但新手期先把 and 写熟。" },
    ],
  },
  {
    id: "l9", title: "回音长廊", icon: "🌀", boss: false,
    desc: "while 循环：让咒语重复生效",
    story: "第三扇门后是一条圆形长廊，你说一句话，回音就重复一遍。「想把一件事做很多遍，不用把咒语抄很多遍——while，就是让程序转圈的咒语。」守卫的声音带着回响。",
    teach: [
      "while 是「当…就一直」：while 后面跟条件，条件成立就反复执行缩进块，直到条件不成立才停。while hp > 0: ——血量大于 0 就一直战斗。",
      "循环三要素：初始值（i = 1）、条件（while i <= 3:）、更新（i = i + 1）。缺了更新，条件永远成立，就是死循环。",
      "死循环：条件永远为 True，程序停不下来。症状是程序卡住不动、输出刷屏。救命招：Ctrl+C 强制停止（VS Code 里点终端再按）。",
      "循环内的代码会完整执行一轮再检查条件：while i < 3: 里的 print 会执行到 i 变成 3 才停。",
      "break 是「立刻跳出」：在循环里遇到 break，整个循环当场结束，跳到循环后面的代码。找到答案就不用再找了的场景用它。",
      "continue 是「跳过这轮」：本轮剩下的代码不执行了，直接回到 while 那一行开始下一轮。筛掉不要的数据用它。",
      "break 和 continue 只能在循环里用，写在循环外面会报 SyntaxError。",
      "循环里能用变量做任意事：累加 total = total + dmg、计数 count = count + 1 是最常见的两个套路。总和一个数、计数一个数，循环前先造好箱子装 0。",
      "i = i + 1 的缩写是 i += 1（加减乘除都有缩写：+=、-=、*=、//=）。两行代码等价，缩写更顺手。",
      "经典套路——倒计时：while n > 0: 显示 n，然后 n -= 1，循环结束后显示「发射！」。顺序：先干活再更新，还是先更新再干活，输出完全不同。",
      "print 的 end 参数：print('x', end=' ') 让显示不换行、用空格隔开。做一行输出 1 2 3 这种效果全靠它。",
    ],
    tutorial: TUTORIALS.l9,
    questions: [
      { type: "predict", code: "i = 1\nwhile i <= 3:\n    print(i)\n    i = i + 1", q: "运行后屏幕会显示什么？",
        options: ["1\n2\n3", "1\n2\n3\n4", "1 1 1 无限刷屏", "只显示 1"],
        answer: 0,
        explain: "i 从 1 开始：显示 1，变 2；显示 2，变 3；显示 3，变 4；4 > 3 条件不成立，循环结束。" },
      { type: "choice", q: "下面哪段代码是死循环？",
        options: ["i = 0\nwhile i < 5:\n    i += 1", "i = 0\nwhile i < 5:\n    print(i)", "i = 5\nwhile i > 0:\n    i -= 1", "i = 0\nwhile i < 3:\n    print(i)\n    i += 1"],
        answer: 1,
        explain: "B 的循环体里没有更新 i，i 永远是 0、永远小于 5——永远转下去。其他三个都有更新。" },
      { type: "judge", q: "break 的作用是跳过本轮循环、直接开始下一轮。", answer: false,
        explain: "反了——那是 continue。break 是整个循环当场结束，一轮都不再转。" },
      { type: "blank", q: "补全关键字：数字不到 10 就一直数下去（补全循环关键字）", code: "n = 1\n___ n < 10:\n    print(n)\n    n += 1", answer: "while",
        explain: "「当…就重复」用 while。条件写在 while 后面，冒号别忘了。" },
      { type: "predict", code: "i = 0\nwhile i < 5:\n    i += 1\n    if i == 3:\n        break\nprint(i)", q: "运行后屏幕会显示什么？",
        options: ["3", "5", "0", "报错"],
        answer: 0,
        explain: "i 变到 3 时命中 break，循环当场结束。最后显示的是 3——break 之后直接跳到循环外。" },
      { type: "predict", code: "i = 0\nwhile i < 4:\n    i += 1\n    if i == 2:\n        continue\n    print(i)", q: "运行后屏幕会显示什么？",
        options: ["1\n3\n4", "1\n2\n3\n4", "2", "什么都不显示"],
        answer: 0,
        explain: "i 是 2 时 continue 跳过本轮的 print，直接回 while 开始下一轮。所以 2 没显示，其他都显示了。" },
      { type: "choice", q: "想在循环里做累加求和（1+2+3+…+10），循环前应该先造什么箱子？",
        options: ["total = 0", "total = 1", "total = 10", "不用造，直接用"],
        answer: 0,
        explain: "累加从 0 开始（加 0 不影响结果）。循环里写 total += i，转完箱子里的就是总和。" },
      { type: "predict", code: "total = 0\ni = 1\nwhile i <= 4:\n    total += i\n    i += 1\nprint(total)", q: "运行后屏幕会显示什么？",
        options: ["10", "4", "15", "1"],
        answer: 0,
        explain: "total 依次加 1、2、3、4，最后是 10。累加套路：箱子先装 0，循环里 +=。" },
      { type: "judge", q: "i += 1 和 i = i + 1 完全等价。", answer: true,
        explain: "对，+= 是缩写。-=、*=、//= 同理，都是「取出、运算、放回」的缩写。" },
      { type: "code", q: "实操：用 while 循环显示 1 到 5（五行输出，每行一个数字）",
        starter: "",
        expected: "1\n2\n3\n4\n5",
        explain: "i = 1 造初始值 → while i <= 5: → 缩进块里 print(i) 然后 i += 1。三要素缺一不可。" },
      { type: "code", q: "实操：用 while 循环算 1+2+3+…+10 的总和，显示结果（一行输出）",
        starter: "",
        expected: "55",
        explain: "total = 0 和 i = 1 两个箱子 → while i <= 10: total += i、i += 1 → 循环外 print(total)。1 加到 10 是 55。" },
      { type: "code", q: "实操：倒计时。n 从 3 开始，显示 3、2、1 各占一行，最后显示「发射！」",
        starter: "",
        expected: "3\n2\n1\n发射！",
        explain: "n = 3 → while n > 0: print(n)、n -= 1 → 循环外 print('发射！')。「发射！」不缩进，属于循环结束后的代码。" },
      { type: "code", q: "实操：hp 从 100 开始，每次被打 30 点（先扣血再显示：hp -= 30 后 print(hp)），只要 hp 一开始仍大于 0 就再挨一次打。被打后的血量都显示出来（哪怕变成负数），循环结束后显示「倒下」",
        starter: "hp = 100\n",
        expected: "70\n40\n10\n-20\n倒下",
        explain: "while hp > 0: 里先 hp -= 30 再 print(hp)。血量轨迹：100→70（进第2轮时 70>0）→40→10→-20（进第4轮时 10>0，扣完变 -20 也显示）。-20 不大于 0，循环结束显示「倒下」——注意循环条件查的是「进入这一轮时」的血量。" },
    ],
  },
  {
    id: "l10", title: "Boss战·抉择大师", icon: "⚔️", boss: true,
    desc: "for / range：终极循环",
    story: "长廊尽头，守卫的真身浮现——一尊巨大的石魔像。「循环你已经会了 while，但真正的抉择大师还掌握着 for。接招吧，修行者！」",
    teach: [
      "for 是「逐个处理」：for i in range(5): 表示 i 依次取 0、1、2、3、4，循环 5 次。range(5) 生成 0 到 4 的数列——从 0 开始，不包含 5。",
      "range 三种用法：range(5) 是 0 到 4；range(1, 6) 是 1 到 5（从 1 开始，不包含 6）；range(0, 10, 2) 是 0、2、4、6、8（第三个参数是步长）。",
      "for 和 while 怎么选：知道要循环几次（数数、遍历）用 for；不知道几次、只看条件（血量大于 0 就打）用 while。",
      "for 不用手动更新：i 会自己变。while 里忘了 i += 1 会死循环，for 天然没这个坑。",
      "累加套路照样能用：total = 0 → for i in range(1, 101): total += i → 1 加到 100 一行搞定。",
      "循环嵌套：for 里面再放 for，外层每转一轮、内层转完一整圈。九九乘法表就是两层循环。",
      "字符串也能 for：for c in 'abc': 会让 c 依次取 'a'、'b'、'c'。in 后面能放一切「可逐个取的东西」。",
      "break / continue 对 for 同样有效：break 跳出整个 for，continue 跳过本轮。",
      "综合套路：for + if 是黄金组合——遍历一堆数据，条件筛选想要的。for i in range(1, 11): if i % 2 == 0: 就挑出了所有偶数。",
    ],
    tutorial: TUTORIALS.l10,
    questions: [
      { type: "predict", code: "for i in range(3):\n    print(i)", q: "运行后屏幕会显示什么？",
        options: ["0\n1\n2", "1\n2\n3", "0\n1\n2\n3", "3"],
        answer: 0,
        explain: "range(3) 生成 0、1、2——从 0 开始，不含 3。循环 3 次，i 依次是 0、1、2。" },
      { type: "predict", code: "for i in range(1, 4):\n    print(i)", q: "运行后屏幕会显示什么？",
        options: ["1\n2\n3", "0\n1\n2\n3", "1\n2\n3\n4", "4"],
        answer: 0,
        explain: "range(1, 4) 从 1 开始到 3 结束（不含 4）。想从 1 数到 N 就写 range(1, N+1)。" },
      { type: "choice", q: "range(0, 10, 2) 生成哪些数？",
        options: ["0、2、4、6、8", "0 到 10 所有数", "2、4、6、8、10", "0、1、2"],
        answer: 0,
        explain: "第三个参数 2 是步长——从 0 开始每次跳 2，到 10 之前停（不含 10）。" },
      { type: "judge", q: "for i in range(5) 会循环 5 次，i 的最后一个值是 5。", answer: false,
        explain: "循环次数确实是 5 次，但 i 的取值是 0 到 4，最后一个值是 4——range 不含结尾数。" },
      { type: "blank", q: "补全关键字：让 i 从 1 取到 10（补全循环关键字）", code: "___ i in range(1, 11):\n    print(i)", answer: "for",
        explain: "「逐个取」用 for。range(1, 11) 是 1 到 10——想包含 10 就得写到 11。" },
      { type: "predict", code: "total = 0\nfor i in range(1, 5):\n    total += i\nprint(total)", q: "运行后屏幕会显示什么？",
        options: ["10", "15", "4", "6"],
        answer: 0,
        explain: "1+2+3+4 = 10。range(1, 5) 是 1、2、3、4，累加进 total 后是 10。" },
      { type: "predict", code: "for i in range(5):\n    if i == 2:\n        continue\n    print(i)", q: "运行后屏幕会显示什么？",
        options: ["0\n1\n3\n4", "0\n1\n2\n3\n4", "2", "0\n1"],
        answer: 0,
        explain: "i 是 2 时被 continue 跳过，其他都显示。for 配 continue 筛数据是常用套路。" },
      { type: "choice", q: "想显示 1 到 20 里所有的偶数，最省事的写法是？",
        options: ["for i in range(2, 21, 2):\n    print(i)", "for i in range(1, 21):\n    if i % 2 == 0:\n        print(i)", "while i < 20:\n    print(i)", "print(range(2, 21, 2))"],
        answer: 0,
        explain: "A 用步长 2 直接从 2 跳到 20，一步到位。B 也对但绕了一圈。C 没初始值会报错；D 会显示 range 对象本身。" },
      { type: "predict", code: "for c in 'hi':\n    print(c)", q: "运行后屏幕会显示什么？",
        options: ["h\ni", "hi", "0\n1", "报错"],
        answer: 0,
        explain: "字符串可以逐字符取。c 依次是 'h' 和 'i'，每个 print 一行。" },
      { type: "judge", q: "for 循环需要在循环体里手动写 i += 1，否则死循环。", answer: false,
        explain: "恰恰相反——for 的 i 自动变化，这是它比 while 安全的地方。手写 i += 1 反而是多余的。" },
      { type: "code", q: "实操：用 for 循环显示 1 到 5（五行输出，每行一个数字）",
        starter: "",
        expected: "1\n2\n3\n4\n5",
        explain: "for i in range(1, 6): 缩进 print(i)。range(1, 6) 是 1、2、3、4、5——含头不含尾。" },
      { type: "code", q: "实操：用 for 循环算 1 到 100 的总和，显示结果（一行输出）",
        starter: "",
        expected: "5050",
        explain: "total = 0 → for i in range(1, 101): total += i → print(total)。1 加到 100 是 5050，高斯小时候就算过。" },
      { type: "code", q: "实操：用 for 循环显示九九乘法表的第一行——1×1 到 1×9 的结果，每个数占一行",
        starter: "",
        expected: "1\n2\n3\n4\n5\n6\n7\n8\n9",
        explain: "for i in range(1, 10): print(1 * i)。range(1, 10) 是 1 到 9。显示结果就是 1 到 9。" },
      { type: "code", q: "实操：用 for 循环显示 1 到 10 中所有的偶数（每个一行，共五行：2、4、6、8、10）",
        starter: "",
        expected: "2\n4\n6\n8\n10",
        explain: "for i in range(2, 11, 2): print(i)——步长 2 直接跳着取。或 for i in range(1, 11): if i % 2 == 0: print(i)。" },
      { type: "code", q: "实操：综合 Boss 题。用 while 循环模拟战斗——hp 从 50 开始，每轮显示「战斗中」再扣 20 血（hp -= 20），只要 hp 大于 0 就继续下一轮，hp 不大于 0 后显示「胜利」",
        starter: "hp = 50\n",
        expected: "战斗中\n战斗中\n战斗中\n胜利",
        explain: "while hp > 0: 缩进块里先 print('战斗中') 再 hp -= 20。血量轨迹：50→30→10→-10，进入前三轮时血量都大于 0，所以「战斗中」显示 3 次。50 除以 20 商 2 余 1——只要有余数就要多打一轮。" },
    ],
  },
  ],
},
{
  id: "ch3", no: "第三章", title: "百宝行囊", sub: "列表 / 字典",
  levels: [
  {
    id: "l11", title: "百宝行囊", icon: "🎒", boss: false,
    desc: "列表：一口气装很多东西",
    story: "战胜石魔像，它裂开的胸口里滚出一个行囊。「背包格子有限，行囊却能装万物。列表（list），就是能装一串东西的魔法行囊。」守卫最后的声音渐渐远去。",
    teach: [
      "列表的写法：用方括号包起来，东西之间用逗号隔开。bag = ['药水', '剑', '盾']。一个箱子只能装一个值，一个行囊能装一串。",
      "访问靠编号（索引）：bag[0] 是第一个、bag[1] 是第二个。编号从 0 开始数——这是编程世界的规矩，第一个是 0 号。",
      "索引从 0 开始的理由：它其实是「偏移量」——离开头多远。第一个东西离开头 0 步，第二个离 1 步。想通这一点就再也不会数错。",
      "数长度用 len()：len(bag) 返回行囊里有几样东西。三个东西 len 是 3，但最后一个的索引是 2（0、1、2）——长度和最后索引永远差 1。",
      "超界会报错：bag 里只有 3 样东西，bag[3] 直接 IndexError: list index out of range。想拿最后一个安全写法是 bag[len(bag) - 1]。",
      "往里加东西：bag.append('弓') 把弓追加到行囊最后。append 后面跟括号，一次加一个。",
      "列表什么都能装：数字、文字混着装也行 [1, '药水', 3]。甚至装另一个列表 [[1, 2], [3, 4]]（嵌套，以后细讲）。",
      "列表也是变量：score_list = [90, 85, 77] 之后 print(score_list) 会显示整个列表，格式是 [90, 85, 77]——带方括号和逗号。",
      "判断东西在不在行囊里：'剑' in bag 结果是 True 或 False。in 配 if 是黄金组合：if '药水' in bag: 就知道带没带药。",
      "列表能加减吗：不能直接 + 数字（会报 TypeError），但 列表 + 列表 是拼接：[1, 2] + [3] 得到 [1, 2, 3]。列表 * 2 是重复：[0] * 3 得到 [0, 0, 0]。",
      "空列表：empty = []。先造个空行囊，之后 append 往里装——收集数据的经典开局。",
    ],
    tutorial: TUTORIALS.l11,
    questions: [
      { type: "choice", q: "bag = ['药水', '剑', '盾']，bag[0] 是什么？",
        options: ["药水", "剑", "盾", "报错"],
        answer: 0,
        explain: "索引从 0 开始——bag[0] 是第一个「药水」。bag[1] 才是「剑」。" },
      { type: "predict", code: "bag = ['药水', '剑', '盾']\nprint(bag[2])", q: "运行后屏幕会显示什么？",
        options: ["盾", "剑", "药水", "报错"],
        answer: 0,
        explain: "bag[0] 药水、bag[1] 剑、bag[2] 盾——三个东西，最后一个是索引 2。" },
      { type: "predict", code: "nums = [10, 20, 30]\nprint(len(nums))", q: "运行后屏幕会显示什么？",
        options: ["3", "2", "30", "10"],
        answer: 0,
        explain: "len() 数的是「有几样东西」——3 个。注意最后一个的索引是 2，不是 3。" },
      { type: "judge", q: "bag 里有 3 样东西，bag[3] 能拿到最后一个。", answer: false,
        explain: "3 样东西的索引是 0、1、2，bag[3] 越界了，报 IndexError。最后一个是 bag[2]。" },
      { type: "blank", q: "补全方法名：把「弓」追加到行囊最后（补全方法）", code: "bag = ['药水', '剑']\nbag.___('弓')", answer: "append",
        explain: "append 是「追加到最后」。注意有括号，东西放括号里。" },
      { type: "predict", code: "bag = ['药水', '剑']\nbag.append('盾')\nprint(bag)", q: "运行后屏幕会显示什么？",
        options: ["['药水', '剑', '盾']", "['盾', '药水', '剑']", "药水 剑 盾", "报错"],
        answer: 0,
        explain: "append 追加到最后。print 整个列表会带方括号和引号原样显示。" },
      { type: "choice", q: "print('剑' in ['药水', '剑', '盾']) 会显示什么？",
        options: ["True", "False", "剑", "报错"],
        answer: 0,
        explain: "「剑」确实在列表里，in 判断结果是 True。in 永远返回布尔值。" },
      { type: "predict", code: "nums = [1, 2]\nnums.append(3)\nprint(len(nums))", q: "运行后屏幕会显示什么？",
        options: ["3", "2", "4", "报错"],
        answer: 0,
        explain: "原来 2 个，append 加了 1 个，len 变成 3。" },
      { type: "predict", code: "a = [1, 2]\nb = [3]\nprint(a + b)", q: "运行后屏幕会显示什么？",
        options: ["[1, 2, 3]", "[4, 5]", "6", "报错"],
        answer: 0,
        explain: "列表 + 列表 是拼接——两个行囊的东西连成一个新行囊。不是数字相加。" },
      { type: "judge", q: "nums = [90, 85]，nums.append(77) 之后 nums 变成 [90, 85, 77]。", answer: true,
        explain: "对，append 把 77 追加到了列表最后。" },
      { type: "code", q: "实操：造一个列表 fruits 装「苹果」「香蕉」「橙子」（已给你写好）。显示第二个水果（一行输出）",
        starter: "fruits = ['苹果', '香蕉', '橙子']\n",
        expected: "香蕉",
        explain: "第二个的索引是 1——从 0 数起。print(fruits[1])。" },
      { type: "code", q: "实操：造空列表 bag（bag = [] 已给你写好）。先追加「剑」，再追加「盾」，最后显示整个列表（一行输出）",
        starter: "bag = []\n",
        expected: "['剑', '盾']",
        explain: "bag.append('剑')、bag.append('盾')、print(bag)。print 整个列表会带方括号、引号、逗号原样显示。" },
    ],
  },
  {
    id: "l12", title: "翻找行囊", icon: "🔍", boss: false,
    desc: "切片 / 修改 / 删除",
    story: "你背着行囊继续赶路，发现东西多了以后翻找成了麻烦事。「想拿中间几样、想换掉旧的、想扔掉不要的——切片、修改、删除，翻找行囊的三式。」路边的精灵商人递给你一张图谱。",
    teach: [
      "切片是「拿一段」：nums[1:3] 拿索引 1 到 2 的（含头不含尾，和 range 一个脾气）。nums = [10, 20, 30, 40] 里 nums[1:3] 是 [20, 30]。",
      "切片省略写法：nums[:2] 从头拿到索引 1；nums[2:] 从索引 2 拿到尾；nums[:] 拿全部（复制一份）。",
      "修改直接赋值：nums[0] = 99 把索引 0 的东西换成 99。列表内容能改——这叫「可变」，字符串反而不能这样改。",
      "删除用 del：del nums[0] 把索引 0 的东西扔掉，后面的自动往前补位。删掉第一个后，原来的第二个变成了新的第一个。",
      "删除还有 remove：nums.remove(20) 按「值」删——找到第一个 20 扔掉。del 按位置删、remove 按值删，各有所长。",
      "遍历列表用 for：for item in bag: 会让 item 依次取行囊里的每样东西。这是第三章最常用的套路，没有之一。",
      "遍历 + 筛选：for n in nums: if n > 10: print(n) ——遍历一堆数，挑出大于 10 的。for + if 组合拳。",
      "遍历带编号：for i in range(len(bag)): print(i, bag[i]) ——i 是索引、bag[i] 是东西，两个都有。",
      "列表里数最大最小求和：max(nums)、min(nums)、sum(nums) 三个内置函数，一行搞定。",
      "排序：nums.sort() 让列表从小到大原地排序（行囊里的东西按顺序摆好）。排序后原列表变了，想保留原样要先复制一份 nums2 = nums[:]。",
    ],
    tutorial: TUTORIALS.l12,
    questions: [
      { type: "predict", code: "nums = [10, 20, 30, 40]\nprint(nums[1:3])", q: "运行后屏幕会显示什么？",
        options: ["[20, 30]", "[10, 20]", "[20, 30, 40]", "[10, 20, 30]"],
        answer: 0,
        explain: "切片含头不含尾：从索引 1 拿到索引 2（不含 3）。20 和 30。" },
      { type: "predict", code: "nums = [10, 20, 30, 40]\nprint(nums[:2])", q: "运行后屏幕会显示什么？",
        options: ["[10, 20]", "[10, 20, 30]", "[30, 40]", "[20]"],
        answer: 0,
        explain: "冒号前不写就是从头开始：nums[:2] 等价 nums[0:2]，拿索引 0 和 1。" },
      { type: "predict", code: "nums = [10, 20, 30]\nnums[0] = 99\nprint(nums)", q: "运行后屏幕会显示什么？",
        options: ["[99, 20, 30]", "[10, 20, 30]", "[99]", "报错"],
        answer: 0,
        explain: "nums[0] = 99 把索引 0 的 10 换成 99，其他不动。" },
      { type: "predict", code: "nums = [10, 20, 30]\ndel nums[0]\nprint(nums)", q: "运行后屏幕会显示什么？",
        options: ["[20, 30]", "[10, 20]", "[10]", "[]"],
        answer: 0,
        explain: "del 删掉索引 0 的 10，后面自动往前补位——20 补成一号位、30 补成二号位。" },
      { type: "choice", q: "nums = [5, 3, 8, 3]，执行 nums.remove(3) 后 nums 变成？",
        options: ["[5, 8, 3]", "[5, 8]", "[3, 8, 3]", "[5, 3, 8]"],
        answer: 0,
        explain: "remove 按值删，只删找到的第一个 3（索引 1 那个），第二个 3 还留着。" },
      { type: "judge", q: "del 按位置删除，remove 按值删除。", answer: true,
        explain: "对。知道删第几个用 del，知道删什么东西用 remove。" },
      { type: "predict", code: "bag = ['剑', '盾', '弓']\nfor item in bag:\n    print(item)", q: "运行后屏幕会显示什么？",
        options: ["剑\n盾\n弓", "0\n1\n2", "['剑', '盾', '弓']", "弓\n盾\n剑"],
        answer: 0,
        explain: "for item in bag 让 item 依次取每样东西，每个 print 一行。顺序就是列表里的顺序。" },
      { type: "predict", code: "nums = [3, 8, 5, 12]\nprint(max(nums))", q: "运行后屏幕会显示什么？",
        options: ["12", "3", "4", "[3, 8, 5, 12]"],
        answer: 0,
        explain: "max() 找最大值。min() 找最小、sum() 求和——三兄弟记住。" },
      { type: "predict", code: "nums = [4, 1, 3]\nnums.sort()\nprint(nums)", q: "运行后屏幕会显示什么？",
        options: ["[1, 3, 4]", "[4, 3, 1]", "[4, 1, 3]", "报错"],
        answer: 0,
        explain: "sort() 从小到大原地排序。原列表本身被改变了。" },
      { type: "blank", q: "补全：删掉 nums 列表里索引 2 的元素（补全关键字）", code: "nums = [1, 2, 3, 4]\n___ nums[2]", answer: "del",
        explain: "del 是关键字不是函数——不用括号，直接 del 列表名[索引]。" },
      { type: "code", q: "实操：nums 装 [4, 7, 2, 9, 1]（已给你写好）。用 for 循环只显示其中大于 3 的数（每行一个）",
        starter: "nums = [4, 7, 2, 9, 1]\n",
        expected: "4\n7\n9",
        explain: "for n in nums: 配 if n > 3: print(n)。遍历 + 筛选，4、7、9 过关，2 和 1 被筛掉。" },
      { type: "code", q: "实操：nums 装 [4, 7, 2, 9, 1]（已给你写好）。显示这个列表的总和（一行输出）",
        starter: "nums = [4, 7, 2, 9, 1]\n",
        expected: "23",
        explain: "print(sum(nums)) 一行搞定；或造 total = 0 用 for 累加。4+7+2+9+1=23。" },
      { type: "code", q: "实操：scores 装 [90, 60, 85, 40]（已给你写好）。用 for 循历数出及格（大于等于 60）的有几个，显示个数（一行输出）",
        starter: "scores = [90, 60, 85, 40]\n",
        expected: "3",
        explain: "count = 0 → for s in scores: if s >= 60: count += 1 → print(count)。90、60、85 三个及格。计数套路和累加一个道理。" },
    ],
  },
  {
    id: "l13", title: "贴标签的口袋", icon: "🧭", boss: false,
    desc: "字典：名字直达口袋",
    story: "翻找行囊终究费劲。精灵商人掏出一件新宝贝——一件缝满口袋的斗篷，每个口袋上都有名牌。「列表靠编号取东西，字典靠名字取东西。hero['hp'] 直接拿到血量，不用数第几个。」",
    teach: [
      "字典的写法：大括号包起来，「键: 值」成对出现，逗号隔开。hero = {'hp': 100, 'mp': 50}。键是名牌、值是口袋里装的东西。",
      "访问靠键：hero['hp'] 拿到 100。不用数编号，喊名字直达——这就是字典和列表最大的区别。",
      "列表 vs 字典：东西有顺序、靠位置区分用列表；东西有名字、靠名字区分用字典。装备栏适合列表，属性面板适合字典。",
      "添加新键值对：hero['exp'] = 0 直接写——键不存在就新建，存在就覆盖。字典比列表多一个「随手加」的本事。",
      "修改也是赋值：hero['hp'] = 80 把血量改成 80。和添加长得一模一样——键存在是改、不存在是加。",
      "删除用 del：del hero['mp'] 把「mp」这个口袋整个撕掉。和列表的 del 一个用法，只是方括号里放键名。",
      "键必须是不可变的：字符串、数字都能当键，列表不能（报 TypeError）。值随便——数字、文字、列表、甚至另一个字典都行。",
      "判断键在不在：'hp' in hero 是 True。避免访问不存在的键——hero['atk'] 不存在会报 KeyError。",
      "数有几个键值对：len(hero)。键值对算一个整体。",
      "KeyError 长相：KeyError: 'atk'——冒号后面就是你访问的那个不存在的键。看到它就知道：键名拼错了，或者还没建。",
      "字典的 print：print(hero) 会显示 {'hp': 100, 'mp': 50}——带大括号、引号、冒号、逗号原样显示。格式对不上判错时仔细看符号。",
    ],
    tutorial: TUTORIALS.l13,
    questions: [
      { type: "predict", code: "hero = {'hp': 100, 'mp': 50}\nprint(hero['hp'])", q: "运行后屏幕会显示什么？",
        options: ["100", "50", "hp", "报错"],
        answer: 0,
        explain: "字典靠键名取值——hero['hp'] 喊「hp」的名拿到 100。" },
      { type: "choice", q: "想建一个存「名字: 职业」的字典，下面哪个写法对？",
        options: ["hero = {'name': '战士', 'job': '剑士'}", "hero = ['name': '战士', 'job': '剑士']", "hero = ('name': '战士')", "hero = {name: 战士}"],
        answer: 0,
        explain: "字典用大括号；键和值都要加引号（都是字符串时）；B 用了方括号；C 用了圆括号；D 没加引号会被当成变量。" },
      { type: "predict", code: "hero = {'hp': 100}\nhero['mp'] = 50\nprint(hero)", q: "运行后屏幕会显示什么？",
        options: ["{'hp': 100, 'mp': 50}", "{'mp': 50}", "{'hp': 100}", "报错"],
        answer: 0,
        explain: "hero['mp'] = 50 键不存在就新建。现在字典里有两对。" },
      { type: "predict", code: "hero = {'hp': 100, 'mp': 50}\nhero['hp'] = 80\nprint(hero['hp'])", q: "运行后屏幕会显示什么？",
        options: ["80", "100", "180", "报错"],
        answer: 0,
        explain: "键存在时赋值是覆盖——血量从 100 改成 80。" },
      { type: "predict", code: "hero = {'hp': 100, 'mp': 50}\ndel hero['mp']\nprint(hero)", q: "运行后屏幕会显示什么？",
        options: ["{'hp': 100}", "{'mp': 50}", "{}", "报错"],
        answer: 0,
        explain: "del hero['mp'] 撕掉 mp 口袋，只剩 hp。" },
      { type: "judge", q: "访问字典里不存在的键会报 KeyError。", answer: true,
        explain: "对。KeyError 后面跟着的就是那个不存在的键名——看到它先检查键名拼没拼错。" },
      { type: "predict", code: "hero = {'hp': 100, 'mp': 50}\nprint(len(hero))", q: "运行后屏幕会显示什么？",
        options: ["2", "4", "150", "报错"],
        answer: 0,
        explain: "len 数的是键值对的数量——两对（hp 一对、mp 一对）。值里的数字不算。" },
      { type: "choice", q: "print('atk' in {'hp': 100, 'mp': 50}) 会显示什么？",
        options: ["False", "True", "报错", "atk"],
        answer: 0,
        explain: "atk 这个键不存在，in 判断是 False。in 检查的是「键」在不在，不看值。" },
      { type: "blank", q: "补全：把 hero 字典的血量改成 60（补全键名）", code: "hero = {'hp': 100}\nhero['___'] = 60", answer: "hp",
        explain: "键名 'hp' 要加引号（字符串键）。这行执行后 hp 变成 60。" },
      { type: "predict", code: "hero = {'name': 'Corrin'}\nprint(hero['name'])", q: "运行后屏幕会显示什么？",
        options: ["Corrin", "name", "{'name': 'Corrin'}", "报错"],
        answer: 0,
        explain: "hero['name'] 拿到值 'Corrin'，print 显示时引号会被脱掉。" },
      { type: "code", q: "实操：hero 字典已给你写好（name 和 hp）。显示「名字是Corrin血量是100」这样的格式？不要——改为分两行：第一行显示名字，第二行显示血量（两行输出）",
        starter: "hero = {'name': 'Corrin', 'hp': 100}\n",
        expected: "Corrin\n100",
        explain: "print(hero['name']) 显示 Corrin（引号自动脱掉），print(hero['hp']) 显示 100。" },
      { type: "code", q: "实操：hero 字典已给你写好（hp 100）。写代码：扣 30 点血（hp 变成 70），再给字典加一个新键 'mp' 装进 50。最后显示整个字典（一行输出）",
        starter: "hero = {'hp': 100}\n",
        expected: "{'hp': 70, 'mp': 50}",
        explain: "hero['hp'] = hero['hp'] - 30（或 -= 30）改血量，hero['mp'] = 50 加新键，print(hero)。print 字典会带大括号引号冒号逗号。" },
    ],
  },
  {
    id: "l14", title: "翻遍口袋", icon: "🗂️", boss: false,
    desc: "字典遍历 / 嵌套",
    story: "斗篷上的口袋越来越多，一个个翻太慢。「遍历所有口袋、口袋里再藏口袋——嵌套与遍历，管理复杂数据的最后两式。」商人的图谱翻到了最后一页。",
    teach: [
      "遍历字典的键：for key in hero: ——key 依次取每个键名。字典也能直接 for，拿到的默认是键。",
      "更清晰的写法 keys()：for key in hero.keys(): 和上面完全等价，但读代码的人一眼看懂你要的是键。",
      "遍历键值对 items()：for key, value in hero.items(): ——一次拿到键和值两个变量。这是字典遍历最常用的姿势。",
      "只遍历值 values()：for v in hero.values(): ——只要值不要键。比如只要所有属性数值。",
      "嵌套字典：字典的值可以是另一个字典。hero = {'武器': {'名字': '铁剑', '攻击': 10}}。取嵌套值要连着走：hero['武器']['攻击'] 拿到 10。",
      "字典装列表：hero = {'技能': ['火球', '冰锥']}。hero['技能'] 拿到列表，hero['技能'][0] 拿到「火球」。一层一层剥。",
      "列表装字典：team = [{'name': '甲', 'hp': 100}, {'name': '乙', 'hp': 80}]。team[0] 是第一个人的字典，team[0]['hp'] 是他的血量——游戏队伍的标准存法。",
      "遍历列表装字典：for member in team: print(member['hp']) ——取出每个人的血量。先取列表元素（字典），再取字典的键。",
      "嵌套的阅读心法：从外往里读，一层一层剥洋葱。hero['武器']['名字'] 读作「hero 的 武器 的 名字」。",
      "改嵌套里的值：hero['武器']['攻击'] = 15 ——定位到最里层再赋值，和普通修改一个道理。",
    ],
    tutorial: TUTORIALS.l14,
    questions: [
      { type: "predict", code: "hero = {'hp': 100, 'mp': 50}\nfor key in hero:\n    print(key)", q: "运行后屏幕会显示什么？",
        options: ["hp\nmp", "100\n50", "hp 100\nmp 50", "报错"],
        answer: 0,
        explain: "直接 for 字典，拿到的默认是键名。想拿值要 hero[key]。" },
      { type: "predict", code: "hero = {'hp': 100, 'mp': 50}\nfor k, v in hero.items():\n    print(k, v)", q: "运行后屏幕会显示什么？",
        options: ["hp 100\nmp 50", "hp\nmp", "100\n50", "报错"],
        answer: 0,
        explain: "items() 每轮给一对键值。print(k, v) 逗号分隔自动变空格。" },
      { type: "predict", code: "hero = {'hp': 100, 'mp': 50}\nfor v in hero.values():\n    print(v)", q: "运行后屏幕会显示什么？",
        options: ["100\n50", "hp\nmp", "150", "报错"],
        answer: 0,
        explain: "values() 只要值。100 和 50 各占一行。" },
      { type: "predict", code: "weapon = {'名字': '铁剑', '攻击': 10}\nprint(weapon['攻击'])", q: "运行后屏幕会显示什么？",
        options: ["10", "攻击", "铁剑", "报错"],
        answer: 0,
        explain: "weapon['攻击'] 按键名拿到值 10。中文键名完全合法。" },
      { type: "predict", code: "hero = {'武器': {'攻击': 10}}\nprint(hero['武器']['攻击'])", q: "运行后屏幕会显示什么？",
        options: ["10", "{'攻击': 10}", "武器", "报错"],
        answer: 0,
        explain: "嵌套字典一层层剥：先 hero['武器'] 拿到内层字典，再 ['攻击'] 拿到 10。" },
      { type: "predict", code: "hero = {'技能': ['火球', '冰锥']}\nprint(hero['技能'][1])", q: "运行后屏幕会显示什么？",
        options: ["冰锥", "火球", "['火球', '冰锥']", "报错"],
        answer: 0,
        explain: "hero['技能'] 拿到列表 ['火球', '冰锥']，[1] 拿到第二个「冰锥」。" },
      { type: "predict", code: "team = [{'hp': 100}, {'hp': 80}]\nprint(team[1]['hp'])", q: "运行后屏幕会显示什么？",
        options: ["80", "100", "180", "报错"],
        answer: 0,
        explain: "team[1] 是第二个字典 {'hp': 80}，['hp'] 拿到 80。列表取人、字典取属性。" },
      { type: "predict", code: "team = [{'hp': 100}, {'hp': 80}]\nfor m in team:\n    print(m['hp'])", q: "运行后屏幕会显示什么？",
        options: ["100\n80", "10080", "hp\nhp", "报错"],
        answer: 0,
        explain: "for 取出每个字典，m['hp'] 取各自的血量。遍历队伍的标准操作。" },
      { type: "blank", q: "补全方法名：遍历字典所有键值对（补全方法）", code: "hero = {'hp': 100}\nfor k, v in hero.___():\n    print(k, v)", answer: "items",
        explain: "items() 给键值对，values() 只给值，keys() 只给键。" },
      { type: "judge", q: "hero = {'bag': ['药水', '剑']}，hero['bag'].append('盾') 能往 bag 列表里加「盾」。", answer: true,
        explain: "对——hero['bag'] 先拿到列表，.append('盾') 就是普通列表操作。嵌套里每层都有全套本事。" },
      { type: "code", q: "实操：hero 字典已给你写好。用 for + items() 遍历，每行显示「键 值」（两行输出）",
        starter: "hero = {'hp': 100, 'mp': 50}\n",
        expected: "hp 100\nmp 50",
        explain: "for k, v in hero.items(): print(k, v)。print 逗号分隔自动加空格。" },
      { type: "code", q: "实操：team 列表已给你写好（两个人各是字典）。用 for 遍历，显示每个人的 hp（两行输出）",
        starter: "team = [{'name': '甲', 'hp': 100}, {'name': '乙', 'hp': 80}]\n",
        expected: "100\n80",
        explain: "for m in team: print(m['hp'])。列表装字典 + for 遍历，游戏队伍就是这么管理的。" },
    ],
  },
  {
    id: "l15", title: "Boss战·行囊大师", icon: "🏆", boss: true,
    desc: "列表 + 字典综合运用",
    story: "斗篷斗篷的主人——百宝行囊的守护者终于现身。「列表管队伍、字典管属性、循环管战斗、条件管抉择——四式合一，方成大师。最后一战，用你学会的一切！」",
    teach: [
      "综合套路总览：列表装一堆同类数据（队伍、背包、成绩单）；字典给单个体贴标签（属性、配置）；for 遍历处理每个；if 筛选想要的。",
      "游戏数据的标准结构：team = [ {'name': ..., 'hp': ..., 'atk': ...}, ... ] ——列表装字典。遍历队伍、更新属性、统计总和全靠这套结构。",
      "统计套路：total = 0 → for m in team: total += m['hp'] → 队伍总血量。和第一章的累加一模一样，只是这次加的是字典里的值。",
      "查找套路：for m in team: if m['name'] == '甲': print(m['hp']) ——按名字找人的标准写法。",
      "修改套路：hero['hp'] -= 30 直接改字典里的值；批量修改就套 for：for m in team: m['hp'] += 10（全员回血）。",
      "筛选套路：for m in team: if m['hp'] > 0: alive.append(m) ——把活着的挑出来装进新列表。先造空列表再 append 是收集的固定起手式。",
      "字符串格式化的新姿势：print(f'血量: {hero[\"hp\"]}') ——f 字符串，引号前加 f，大括号里放变量或表达式，直接嵌进文字。比逗号拼接更灵活。",
      "f-string 细节：f'第{i}轮' 里 {i} 会被换成 i 的值。大括号里还能写算式 f'总和: {a + b}'。新手掌握 {变量} 就够用。",
      "读复杂代码的心法：从数据结构倒推。看到 for m in team: 就知道 team 是列表、m 是字典；看到 m['hp'] 就知道在取属性。结构清楚了，代码就透明了。",
      "出错时的排查顺序：先看报错最后一行（什么错）→ 再看行号（哪里错）→ 最后检查那一行的方括号、引号、键名拼写。八成问题这三步能解决。",
    ],
    tutorial: TUTORIALS.l15,
    questions: [
      { type: "predict", code: "team = [{'hp': 100}, {'hp': 80}]\ntotal = 0\nfor m in team:\n    total += m['hp']\nprint(total)", q: "运行后屏幕会显示什么？",
        options: ["180", "100", "80", "2"],
        answer: 0,
        explain: "累加套路用在字典值上：100 + 80 = 180。" },
      { type: "predict", code: "team = [{'name': '甲', 'hp': 50}, {'name': '乙', 'hp': 100}]\nfor m in team:\n    if m['hp'] > 60:\n        print(m['name'])", q: "运行后屏幕会显示什么？",
        options: ["乙", "甲", "甲\n乙", "什么都不显示"],
        answer: 0,
        explain: "只有乙的 hp 超过 60，所以只显示乙。筛选 + 取属性的组合。" },
      { type: "choice", q: "print(f'血量: {100 - 30}') 会显示什么？",
        options: ["血量: 70", "血量: {100 - 30}", "血量: 100 - 30", "报错"],
        answer: 0,
        explain: "f 字符串的大括号里会先算表达式再嵌进去。100-30 算出 70 填进去。" },
      { type: "predict", code: "hero = {'hp': 100}\nhero['hp'] -= 30\nprint(hero['hp'])", q: "运行后屏幕会显示什么？",
        options: ["70", "100", "130", "报错"],
        answer: 0,
        explain: "-= 缩写在字典值上照样好用——取出 100、减 30、放回。" },
      { type: "predict", code: "nums = [1, 2, 3]\nnums.append(4)\nprint(len(nums))", q: "运行后屏幕会显示什么？",
        options: ["4", "3", "10", "报错"],
        answer: 0,
        explain: "append 加一个，len 变 4。列表三件套：append 加、len 数、索引取。" },
      { type: "predict", code: "d = {'a': 1, 'b': 2}\nprint(d['a'] + d['b'])", q: "运行后屏幕会显示什么？",
        options: ["3", "12", "a1b2", "报错"],
        answer: 0,
        explain: "分别取两个键的值 1 和 2，加法是数字相加得 3。" },
      { type: "judge", q: "alive = [] 之后 alive.append(m) 是「收集」套路的标准起手式。", answer: true,
        explain: "对——先造空列表，循环里符合条件就 append 进去。筛出来的数据就有了着落。" },
      { type: "predict", code: "for i in range(2):\n    print(f'第{i}轮')", q: "运行后屏幕会显示什么？",
        options: ["第0轮\n第1轮", "第1轮\n第2轮", "第i轮\n第i轮", "报错"],
        answer: 0,
        explain: "range(2) 是 0 和 1，f-string 把 i 的值嵌进文字。记得 range 从 0 开始。" },
      { type: "choice", q: "想把 team 里所有人的名字连起来显示成「甲 乙」，哪个思路对？",
        options: ["for m in team: print(m['name'], end=' ')", "print(team['name'])", "print(team.name)", "for name in team: print(name)"],
        answer: 0,
        explain: "B/C 把列表当字典用会报错；D 拿到的是字典不是名字。A 用 end=' ' 不换行 + 空格分隔。" },
      { type: "predict", code: "bag = ['剑', '药水', '盾']\nprint(bag[-1])", q: "运行后屏幕会显示什么？",
        options: ["盾", "剑", "报错", "3"],
        answer: 0,
        explain: "负索引从后往前数：-1 是最后一个、-2 是倒数第二个。取最后一个最省事的写法。" },
      { type: "code", q: "实操：team 已给你写好。显示队伍总血量（一行输出，一个数字）",
        starter: "team = [{'name': '甲', 'hp': 100}, {'name': '乙', 'hp': 80}]\n",
        expected: "180",
        explain: "total = 0 → for m in team: total += m['hp'] → print(total)。100 + 80 = 180。" },
      { type: "code", q: "实操：team 已给你写好。全员回血：每人 hp 加 10。最后显示甲的血量（一行输出）",
        starter: "team = [{'name': '甲', 'hp': 100}, {'name': '乙', 'hp': 80}]\n",
        expected: "110",
        explain: "for m in team: m['hp'] += 10 ——批量修改每个字典的值。甲的血量 100+10=110。" },
      { type: "code", q: "实操：nums 已给你写好。用 for 循环把大于 5 的数收集进新列表 big，最后显示 big（一行输出）",
        starter: "nums = [3, 8, 5, 12, 1]\n",
        expected: "[8, 12]",
        explain: "big = [] 起手 → for n in nums: if n > 5: big.append(n) → print(big)。print 列表带方括号逗号。" },
      { type: "code", q: "实操：hero 字典已给你写好（含 name 和 hp）。用 f-string 显示「Corrin的血量是100」（一行输出，注意格式）",
        starter: "hero = {'name': 'Corrin', 'hp': 100}\n",
        expected: "Corrin的血量是100",
        explain: "print(f\"{hero['name']}的血量是{hero['hp']}\") ——f-string 大括号里放变量，字符串拼接最顺手的方式。用逗号拼接 print(hero['name'], '的血量是', hero['hp']) 也行但中间会有空格。" },
      { type: "code", q: "实操：终极 Boss 题。monster 装着 {'hp': 100}。用 while 循环战斗：每轮怪物扣 40 血（hp -= 40），只要血量大于 0 就显示「攻击！」，血量不大于 0 后显示「击败！」。最后另起一行显示总攻击次数（就一个数字）",
        starter: "monster = {'hp': 100}\n",
        expected: "攻击！\n攻击！\n攻击！\n击败！\n3",
        explain: "count = 0 起手 → while monster['hp'] > 0: 里先 monster['hp'] -= 40，再 print('攻击！')，再 count += 1 → 循环外显示「击败！」和 count。血量轨迹：100→60→20→-20，三轮都进了循环（进第三轮时 hp=20 仍大于 0），所以攻击！显示 3 次、count 是 3。" },
    ],
  },
  ],
},
];

/** 扁平化所有关卡（带章节 id 前缀） */
export function allLevels(): {chapterId: string, chapterTitle: string, level: import("./types").Level}[] {
  const out: {chapterId: string, chapterTitle: string, level: import("./types").Level}[] = [];
  for (const ch of COURSES) {
    if (ch.locked) continue;
    for (const lv of ch.levels) {
      out.push({ chapterId: ch.id, chapterTitle: ch.title, level: lv });
    }
  }
  return out;
}

/** 找关卡 by id */
export function findLevel(levelId: string): {chapterId: string, chapterTitle: string, level: import("./types").Level} | null {
  return allLevels().find(x => x.level.id === levelId) || null;
}

/** 下一关 id（线性解锁） */
export function nextLevelId(levelId: string): string | null {
  const list = allLevels();
  const idx = list.findIndex(x => x.level.id === levelId);
  if (idx < 0 || idx >= list.length - 1) return null;
  return list[idx + 1].level.id;
}
