import type { Chapter } from "./types";

/* PyLand 课程数据 —— 从 HTML 版 COURSES 移植
   内容更新只改这个文件，UI 逻辑不用碰。 */

export const COURSES: Chapter[] = [
{
  id: "ch1", no: "第一章", title: "初识咒语",
  sub: "print · 变量 · input · 数据类型",
  levels: [
  {
    id: "l1", title: "第一句咒语", icon: "🗣️", boss: false,
    desc: "print()：让大陆听见你",
    story: "你踏进 PyLand 的入门村。村长格伦捋着胡子说：“每个代码术士的第一步，都是让大陆听见你的声音。来，念出你的第一句咒语——print。”",
    teach: [
      "print() 是让计算机说话的咒语。括号里放什么，屏幕就显示什么。这个括号和引号都必须是英文半角——中文的（）和「“”」计算机不认。",
      '想显示文字，要给文字加引号：print("你好")。引号里的内容叫「字符串」，空格、标点都会原样保留，显示时引号本身不会出现。',
      '单引号双引号都行：print(\'你好\') 和 print("你好") 效果一样，但必须成对——开头双结尾单会报错。',
      "想显示数字或算式，直接写：print(42) 或 print(3 + 4)——算式会先计算，再把结果显示出来。",
      "四则运算符长这样：+ 加、- 减、* 乘、/ 除。没有 × 和 ÷，乘除用星号和斜杠。乘除还遵循先乘除后加减：print(1 + 2 * 3) 是 7 不是 9。",
      "print() 自带换行：一次 print 显示完，光标自动跳到下一行。两个 print 就是两行，不用自己管换行。",
      "# 后面是注释：写给人看的笔记，计算机直接忽略。可以独占一行，也可以跟在代码后面。好注释是给三个月后的自己看的。",
      "Python 区分大小写：print 是咒语，Print / PRINT 都不认识——会报 NameError。",
      '括号里可以放多个东西，用逗号隔开：print("血量", 100) 会显示「血量 100」——逗号的位置自动变空格。这招比 + 拼接省事，还不会报错。',
      "常见报错长相：SyntaxError 多半是引号/括号没配对，或者用了中文符号；NameError 多半是拼写错了（比如 Print）。",
      "新手心法：报错不可怕。看报错最后一行 + 检查引号括号是不是英文半角，八成的错自己就能修。",
    ],
    questions: [
      { type: "choice", q: "哪句咒语能让屏幕显示「你好，PyLand」？",
        options: ['print("你好，PyLand")', 'Print("你好，PyLand")', 'print(你好，PyLand)', '你好.print("PyLand")'],
        answer: 0,
        explain: "B 的 Print 首字母大写了，Python 不认；C 的文字没加引号，计算机会当成代码名而报错；D 的顺序写反了。print 在前，内容在括号里。" },
      { type: "predict", code: 'print("A")\nprint("B")', q: "运行后屏幕会显示什么？",
        options: ["AB 挤在同一行", "A 和 B 各占一行", "只显示 A", "直接报错"],
        answer: 1,
        explain: "每个 print() 自带一次换行。想挤在同一行需要别的咒语，以后再学。" },
      { type: "blank", q: "补全咒语，让屏幕显示「出发！」", code: '___("出发！")', answer: "print",
        explain: "让计算机说话的咒语是 print，注意全小写。" },
      { type: "judge", q: "print() 每显示一次内容，最后都会自动换行。", answer: true,
        explain: "对，换行是 print 自带的默认行为，不用你操心。" },
      { type: "predict", code: 'print(2 * 3)', q: "运行后屏幕会显示什么？",
        options: ["6", "23", "2 * 3", "报错"],
        answer: 0,
        explain: "乘法用星号 *。print 里的算式先计算再显示，结果是 6。" },
      { type: "choice", q: "下面哪一行是 Python 的注释？",
        options: ["// 这行是注释", "# 这行是注释", "print(注释)", "/* 这行是注释 */"],
        answer: 1,
        explain: "Python 用 # 号写注释。// 和 /* */ 是其他语言的写法。" },
      { type: "predict", code: 'print(3 + 4)', q: "运行后屏幕会显示什么？",
        options: ["3 + 4", "7", "3+4", "报错"],
        answer: 1,
        explain: "print 里的算式会先计算，再把结果 7 显示出来。" },
      { type: "blank", q: "补全引号里的内容，让屏幕显示 hello", code: 'print("___")', answer: "hello",
        explain: "引号里写什么就显示什么。注意 hello 全小写。" },
      { type: "judge", q: 'print("你好") 和 print(\'你好\') 效果完全一样。', answer: true,
        explain: "双引号、单引号都可以包文字，只要成对出现，效果一样。" },
      { type: "code", q: "实操：亲手写开场咒语。第一行注释已给你写好，接着先显示「准备……」，再显示「出发！」",
        starter: "# 冒险开始\n",
        expected: "准备…\n出发！",
        explain: "两个 print 各管一行，顺序反了输出也会反——程序永远从上往下执行。" },
    ],
  },
  {
    id: "l2", title: "魔法容器", icon: "📦", boss: false,
    desc: "变量：贴了标签的箱子",
    story: "铁匠安娜带你走进仓库，里面全是贴着标签的箱子。“变量就是贴了标签的魔法箱子——标签是名字，箱子里装着数据。想要什么，喊标签就行。”",
    teach: [
      "hp = 100 的意思是：把 100 装进名叫 hp 的箱子。= 不是「等于」，是「装进去」（赋值）。念的时候念「装进去」，别念「等于」。",
      "箱子里的东西随时可以换：hp = 100 之后再写 hp = 80，箱子里就是 80 了——永远以最后一次为准。",
      '想看箱子里装了什么：print(hp)。注意——print(hp) 显示 100，而 print("hp") 显示 hp 这两个字母。带不带引号，天差地别。',
      "hp = hp - 30 的意思是：把箱子里的数取出来减 30，再放回箱子。等号右边先算完，才装回去。",
      'b = a 是「抄一份」：把 a 箱子里的值抄进 b。之后 a 再怎么变，跟 b 没关系了——抄的是值，不是箱子本身。',
      "变量名规则：只能用字母、数字、下划线；不能以数字开头；不能用 print、if、class 这类被咒语系统占用的关键字。",
      "起名习惯：全小写 + 下划线，比如 max_hp、player_name、total_damage。看名字就知道装什么，是最重要的起名原则——别起 a、b、xxx 这种名字。",
      "这些名字都不合法：2level（数字开头）、my-name（横线会被当成减号）、my name（不能有空格）。",
      "变量名区分大小写：HP、hp、Hp 是三个不同的箱子。别自己坑自己，统一用小写。",
      '箱子什么都能装：数字、文字、以后学的列表字典都行。x = "Corrin" 和 x = 42 都是合法操作。',
      "变量必须先造再用：print(level) 之前从没写过 level = …，会报 NameError——意思是「不认识这个名字」。",
      "==（两个等号连着）才是「等于」的判断。现在先记住长相别搞混，第二章天天用。",
    ],
    questions: [
      { type: "choice", q: '执行 name = "Corrin" 之后，name 里装的是什么？',
        options: ["name 这四个字母", "Corrin 这串文字", "Corrin 外面还带引号", "会报错"],
        answer: 1,
        explain: "引号只是「这是文字」的标记，装进箱子时引号会被脱掉，箱子里是 Corrin。" },
      { type: "predict", code: "x = 5\nx = 8\nprint(x)", q: "运行后屏幕会显示什么？",
        options: ["5", "8", "58", "报错"], answer: 1,
        explain: "后面一次赋值会覆盖前面。x 先装 5，再装 8，打开箱子看到的就是 8。" },
      { type: "choice", q: "哪句咒语能创建名叫 coin 的箱子，并装进 50？",
        options: ["coin == 50", "coin = 50", "50 = coin", "coin: 50"], answer: 1,
        explain: "赋值用单个等号 =，箱子名在左、值在右。== 是「比较是否相等」，不是装东西。" },
      { type: "judge", q: "变量一旦赋值，里面的值就再也不能更改了。", answer: false,
        explain: "变量箱子的核心特性就是随时可换。重新赋值即覆盖。" },
      { type: "predict", code: "a = 10\nb = a\na = 20\nprint(b)", q: "运行后屏幕会显示什么？",
        options: ["20", "10", "1020", "报错"], answer: 1,
        explain: "b = a 是把 a 箱子里的 10 抄一份装进 b。之后 a 换成 20，跟 b 没关系了。" },
      { type: "choice", q: "下面哪个是合法的变量名？",
        options: ["2level", "my-name", "level_2", "print"], answer: 2,
        explain: "A 数字开头不行；B 里的横线会被当成减号；D 的 print 是关键字，被咒语系统占用了。下划线是唯一能用的符号。" },
      { type: "predict", code: 'spell = "魔法"\nprint(spell)', q: "运行后屏幕会显示什么？",
        options: ["spell", "魔法", "\"魔法\"", "报错"], answer: 1,
        explain: "print(spell) 打开的是箱子，显示箱中内容；想显示 spell 这串字母得写 print(\"spell\")。" },
      { type: "judge", q: "hp = 100 里的 = 读作「等于」，意思是两边一样。", answer: false,
        explain: "= 是赋值（装进去），不是等于。想知道两边是否相等要用 ==。" },
      { type: "blank", q: "把 99 装进名叫 mp 的箱子（补全符号）", code: "mp ___ 99", answer: "=",
        explain: "装进去的符号是等号 =，念作「赋值」，不是「等于」。" },
      { type: "blank", q: "创建名叫 hp 的箱子，装进 100（补全变量名）", code: "___ = 100", answer: "hp",
        explain: "变量名在等号左边。取名要合法：不用数字开头、不用横线。" },
      { type: "code", q: "实操：造一个名叫 level 的箱子装 1，先显示箱子里的值，再把箱中数加 1，最后显示「升级！」（两行输出）",
        starter: "",
        expected: "1\n升级！",
        explain: 'level = 1 造箱子 → print(level) 显示 1 → level = level + 1 → print("升级！")。变量没造就使用会报错。' },
      { type: "code", q: "实操：造一个名叫 x 的箱子装 5，把 x 加上 3 放回去，先显示 x，再显示「完成」（两行输出）",
        starter: "",
        expected: "8\n完成",
        explain: 'x = x + 3 是「取出、加 3、放回」，所以 x 变成 8，再 print(x)、print("完成")。' },
    ],
  },
  {
    id: "l3", title: "与大陆对话", icon: "👂", boss: false,
    desc: "input()：程序竖起耳朵",
    story: "旅店老板娘米娅能记住每位旅人的名字。“input() 就是让程序竖起耳朵——它先问你一句话，然后耐心等你输入，再把你的话装进变量箱子里。”",
    teach: [
      'name = input("你叫什么？") → 先显示提示语「你叫什么？」，然后程序停住等你输入，按回车后输入内容装进 name。',
      "input() 括号里也可以留空，但用户会一脸懵不知道要输什么——养成写提示语的习惯。",
      "大坑预警：input() 收到的永远是文字（字符串）！哪怕你输入 18，装进箱子的也是 \“18\” 这串文字，不是数字。",
      '文字数字不分清会出事："3" * 2 得到 33（重复两遍），不是 6；"3" + 1 直接报错。',
      '转换咒语三件套：int("18") 变整数 18、float("1.8") 变小数、str(18) 整数变文字。转的方向想清楚再转。',
      'int() 只认「长得像整数」的文字：int("18") 没问题，但 int("abc") 或 int("3.5") 会报 ValueError——它不猜，转不动就罢工。',
      '常见组合技：age = int(input("年龄？")) —— 一行完成「收话 + 转数字」。读代码从里往外：先 input 收到文字，再 int 转成数字。',
      "提示语只显示一次；你输入的内容不会自动显示在屏幕上——想回显得自己 print。",
      "交互程序的固定套路：input 收集 → int/float 转类型 → 变量做计算 → print 输出结果。四步走完就是一个小程序。",
      "记忆口诀：input 进来的都当文字。要用它算数，先过 int() / float() 这道门。",
    ],
    questions: [
      { type: "choice", q: '执行 age = input("请输入年龄")，用户输入了 18。age 里装的是什么？',
        options: ["整数 18", "文字 \"18\"", "小数 18.0", "报错"], answer: 1,
        explain: "input 收到的永远是字符串。它是文字「18」，不是数字 18——这就是新手最常踩的坑。" },
      { type: "predict", code: 'n = input("输入数字")\nprint(n * 2)\n（用户输入了 3）', q: "运行后屏幕会显示什么？",
        options: ["6", "33", "3", "报错"], answer: 1,
        explain: 'n 是文字 "3"。文字乘 2 不是算数学，是「重复两遍」→ 33。想得到 6 得先 int(n)。' },
      { type: "judge", q: 'input("你叫什么？") 里的提示语会显示在屏幕上。', answer: true,
        explain: "括号里的文字就是给用户看的提示：先显示提示，再等待输入。" },
      { type: "judge", q: "input() 收到的内容可以直接和数字相加。", answer: false,
        explain: '文字和数字不能直接相加，"3" + 1 会报错。先用 int() 转换。' },
      { type: "predict", code: 'n = int(input("输入数字"))\nprint(n * 2)\n（用户输入了 4）', q: "运行后屏幕会显示什么？",
        options: ["8", "44", "4", "报错"], answer: 0,
        explain: "int() 把输入的文字 4 转成数字 4，4 × 2 = 8。对比上一题：转不转，结果天差地别。" },
      { type: "choice", q: "想让输入的数字做加法，哪种写法是对的？",
        options: ["n = input() + 1", "n = int(input()) + 1", "n = input(int())", "int = n + 1"], answer: 1,
        explain: "先把输入转成整数，再做加法。A 是文字加数字，报错；C 顺序写反；D 把变量名写成 int 了。" },
      { type: "blank", q: "补全咒语：把用户输入直接转成整数装进 age", code: 'age = ___(input("年龄"))', answer: "int",
        explain: "int() 是把文字转整数的咒语。转小数用 float()。" },
      { type: "blank", q: "补全咒语：把用户输入的体重转成小数装进 w", code: 'w = ___(input("体重"))', answer: "float",
        explain: "float() 把文字转成小数。体重身高这类带小数点的数用它。" },
      { type: "predict", code: 'name = input("名字")\nprint("你好，" + name)\n（用户输入了 Corrin）', q: "运行后屏幕会显示什么？",
        options: ["你好，Corrin", "你好，+ name", "你好，name", "报错"], answer: 0,
        explain: "文字 + 文字 = 拼接。引号里的原样显示，变量打开箱子取值。" },
      { type: "code", q: "实操：age 箱子已经造好（见起始代码）。显示明年的年龄（一行输出）",
        starter: "age = 18\n",
        expected: "19",
        explain: "print(age + 1) 直接算完显示。也可以先 age = age + 1 再 print(age)，两种都对。" },
    ],
  },
  {
    id: "l4", title: "四系元素", icon: "💎", boss: false,
    desc: "数据类型：万物归四系",
    story: "元素神殿里悬浮着四块水晶，祭司说：“PyLand 万物皆属四系——文字 str、整数 int、小数 float、真伪 bool。分不清元素系别，咒语就会失控。”",
    teach: [
      'str 字符串：被引号包裹的文字。"你好"、\'a\'、"18" 都是——只要带引号，哪怕内容是数字，它也是文字。',
      "int 整数：42、-7、0。不带小数点的完整数。",
      "float 浮点数：带小数点的数，3.14、-0.5，甚至 3.0（小数部分是 0 也算 float）。",
      "bool 布尔：只有 True 和 False 两个值（首字母必须大写），表示真和假——第二章做判断时的主角。",
      "type(x) 是验明元素系的咒语：type(42) → <class 'int'>，type(\“42\”) → <class 'str'>。拿不准就问它。",
      "一眼分辨技巧：带引号全是 str；带小数点是 float；True/False 是 bool；光秃秃的整数才是 int。",
      '转换咒语：int("42") 文字变整数、str(42) 整数变文字、float(3) 变 3.0。int(3.9) 是 3——直接砍掉小数（截断），不是四舍五入。',
      "想要四舍五入用 round()：round(3.5) → 4，round(3.4) → 3。",
      '文字 + 文字 = 拼接："Py" + "Land" → PyLand，中间不会自动加空格。文字 + 数字 = 直接报错，Python 不会自作主张帮你转。',
      '文字 * 数字 = 重复："ha" * 3 → hahaha。这是字符串专属玩法（你已经在 input 关见过 "3" * 2 = 33 了）。',
      "除法 / 的结果永远是 float：10 / 2 是 5.0 不是 5。想要整数结果用整除 //：10 // 2 → 5，7 // 2 → 3（砍掉余数）。",
      "Python 没有 double 这个类型（那是 C / Java 的叫法），小数统一叫 float。",
    ],
    questions: [
      { type: "choice", q: "3.14 属于哪一系元素？",
        options: ["int 整数", "float 浮点数", "str 字符串", "bool 布尔"], answer: 1,
        explain: "带小数点的数就是 float。哪怕 3.0 也是 float 而不是 int。" },
      { type: "predict", code: "print(int(3.9))", q: "运行后屏幕会显示什么？",
        options: ["4", "3", "3.9", "报错"], answer: 1,
        explain: "int() 转换是直接砍掉小数部分（截断），不是四舍五入。想要四舍五入要用 round()。" },
      { type: "judge", q: '"18" 和 18 是一样的东西。', answer: false,
        explain: '"18" 是文字（str），18 是整数（int）。文字不能做数学运算，这是两码事。' },
      { type: "predict", code: 'print("Py" + "Land")', q: "运行后屏幕会显示什么？",
        options: ["PyLand", "Py Land", "Py\nLand", "报错"], answer: 0,
        explain: "文字 + 文字 = 首尾拼接。中间不会自动加空格。" },
      { type: "judge", q: "3.0 是 float 类型，不是 int。", answer: true,
        explain: "只要带小数点，哪怕小数部分是 0，也是 float。" },
      { type: "choice", q: "type(True) 会返回什么？",
        options: ["<class 'bool'>", "<class 'str'>", "<class 'int'>", "报错"], answer: 0,
        explain: "True 和 False 是布尔值。注意首字母大写——true 是错的写法。" },
      { type: "predict", code: 'print("Py" + 2)', q: "运行后屏幕会显示什么？",
        options: ["Py2", "2Py", "报错", "Py"], answer: 2,
        explain: "文字 + 数字会报错！Python 不自动帮你转类型。想拼接要写 \"Py\" + str(2)。" },
      { type: "predict", code: "print(int(7 / 2))", q: "运行后屏幕会显示什么？",
        options: ["3", "3.5", "4", "报错"], answer: 0,
        explain: "7 / 2 = 3.5，int() 再砍掉小数 → 3。除法结果永远是 float，想整除可以用 7 // 2。" },
      { type: "blank", q: "补全咒语：把整数 42 变成文字 \"42\"", code: 'text = ___(42)', answer: "str",
        explain: "str() 是万物变文字的咒语。" },
      { type: "choice", q: "下面哪个值是 bool 类型？",
        options: ['"True"', 'true', 'True', '1'], answer: 2,
        explain: 'A 是文字（有引号）；B 首字母小写不合法；D 是整数。只有 True 是布尔。' },
      { type: "code", q: "实操：用 str() 把整数 42 变成文字，和「生命值：」拼接后显示（一行输出）",
        starter: "",
        expected: "生命值：42",
        explain: 'print("生命值：" + str(42))。文字 + 整数会报错，必须先 str() 转换再拼接。' },
      { type: "blank", q: "补全咒语：把文字 \"42\" 转成数字，让屏幕显示 50", code: 'print(___("42") + 8)', answer: "int",
        explain: 'int("42") 把文字转成整数 42，42 + 8 = 50。不转换的话文字加数字直接报错。' },
    ],
  },
  {
    id: "l5", title: "Boss 战 · 史莱姆王", icon: "👑", boss: true,
    desc: "第一章综合试炼",
    story: "村口的史莱姆王拦住了去路，它浑身果冻般的身体里封印着第一章的所有咒语。“答对我全部的问题，我就认你做 PyLand 的见习代码术士。答错……也没事，你可以重试，但我可要嘲笑你了。”",
    teach: [
      "Boss 战大部分没有新知识——全是你学过的：print、变量、input、数据类型。",
      "新增「实操编程」题：你写的代码会被真的 Python 引擎运行，输出和期望一模一样才算过。报错不扣分随便试，输出错了才计一次失误。",
      "运算全家桶（今天多认识三个）：+ - * / 老四样；// 整除（7 // 2 = 3）；% 取余数（7 % 2 = 1）；** 乘方（2 ** 3 = 8）。",
      "复习清单①print 三要素：全小写、英文括号、文字加引号。",
      "复习清单②变量：先造再用；起名全小写加下划线；b = a 抄的是值。",
      "复习清单③input 进来全是文字，要算数先 int() / float()。",
      "复习清单④类型：带引号是 str，带小数点是 float，True/False 是 bool；拿不准 type() 问。",
      "稳住，先想清楚每行代码「谁先谁后、箱子里装的是什么类型」，再作答。",
      "全部首答答对 = 3星 + 额外 XP。失误了也能过，但星星会少。",
    ],
    questions: [
      { type: "choice", q: "让屏幕显示「战斗开始」，哪句是对的？",
        options: ['print("战斗开始")', 'Print("战斗开始")', 'print(战斗开始)', '"战斗开始".print()'], answer: 0,
        explain: "老规矩：print 全小写、文字加引号、print 在前。" },
      { type: "predict", code: "hp = 50\nhp = hp - 20\nprint(hp)", q: "运行后屏幕会显示什么？",
        options: ["50", "20", "30", "报错"], answer: 2,
        explain: "hp 先装 50，再自减 20 变 30。hp = hp - 20 是「取出-20-放回」。" },
      { type: "predict", code: "print(10 / 2)", q: "运行后屏幕会显示什么？",
        options: ["5", "5.0", "2", "报错"], answer: 1,
        explain: "Python 的除号 / 结果永远是 float。想要整数结果用 // ：10 // 2 才是 5。" },
      { type: "choice", q: "下面哪个「元素系别」在 Python 里根本不存在？",
        options: ["str", "int", "float", "double"], answer: 3,
        explain: "double 是 C / Java 里的类型，Python 没有。Python 的小数叫 float。" },
      { type: "predict", code: 'a = "10"\nb = 3\nprint(a * b)', q: "运行后屏幕会显示什么？",
        options: ["30", "101010", "103", "报错"], answer: 1,
        explain: 'a 是文字 "10"，文字 × 3 = 重复三遍 → 101010。想算 30 要 int(a) * b。' },
      { type: "blank", q: "补全咒语：显示变量 power 箱子里的值", code: "___(power)", answer: "print",
        explain: "print(power) 不加引号——加引号就变成显示 power 这串字母了。" },
      { type: "judge", q: "input() 返回的内容可以直接和数字相加。", answer: false,
        explain: "input 永远返回字符串。先 int() 转换才能做数学。" },
      { type: "judge", q: "10 // 3 的结果是 3.3333……", answer: false,
        explain: "// 是整除（只取整数部分）：10 // 3 = 3。想得到 3.333… 用 / 。" },
      { type: "predict", code: 'hp = 100\nmp = "50"\nprint(hp - int(mp))', q: "运行后屏幕会显示什么？",
        options: ["50", "150", "10050", "报错"], answer: 0,
        explain: 'int("50") 先把文字转成 50，100 - 50 = 50。不转换直接相减会报错。' },
      { type: "judge", q: 'print("2" + "3") 会显示 23。', answer: true,
        explain: '文字 + 文字是拼接不是加法："2" + "3" = "23"。想算 5 要先转成数字。' },
      { type: "code", q: "实操：name 箱子已经造好。显示「你好，Corrin」（一行输出，逗号用中文逗号）",
        starter: 'name = "Corrin"\n',
        expected: "你好，Corrin",
        explain: 'print("你好，" + name)——引号里的原样显示，name 开箱取值，+ 把两段文字拼起来。' },
      { type: "blank", q: "补全咒语：把文字 \"999\" 转成整数装进 gold", code: 'gold = ___("999")', answer: "int",
        explain: "金币数量是整数，用 int() 转换。练到第三次，形成肌肉记忆！" },
      { type: "choice", q: "下面哪个变量名是合法的？",
        options: ["9life", "life-value", "life_value", "class"], answer: 2,
        explain: "数字不能开头；横线会被当减号；class 是关键字。下划线永远安全。" },
      { type: "predict", code: "print(type(3))", q: "运行后屏幕会显示什么？",
        options: ["<class 'int'>", "<class 'float'>", "<class 'str'>", "3"], answer: 0,
        explain: "3 是整数，type() 验明正身返回 <class 'int'>。" },
      { type: "code", q: "实操：造 dmg1 装 30、dmg2 装 45，显示两者之和（一行输出）",
        starter: "# 计算总伤害\n",
        expected: "75",
        explain: "dmg1 = 30、dmg2 = 45，然后 print(dmg1 + dmg2)。也可以先 total = dmg1 + dmg2 再 print(total)。" },
    ],
  },
  ],
},
{
  id: "ch2", no: "第二章", title: "岔路抉择", sub: "if / else / 循环 · 敬请期待", locked: true, levels: [],
},
{
  id: "ch3", no: "第三章", title: "百宝行囊", sub: "列表 / 字典 / 元组 · 敬请期待", locked: true, levels: [],
},
];

/** 扁平化所有关卡（带章节 id 前缀） */
export function allLevels(): {chapterId: string, chapterTitle: string, level: import("./types").Level}[] {
  const out: {chapterId: string, chapterTitle: string, level: import("./types").Level}[] = [];
  for (const ch of COURSES) {
    if (ch.locked) continue;
    for (const lv of ch.levels) {
      out.push({ chapterId: ch.id, chapterTitle: ch.title, level: lv });
    }
  }
  return out;
}

/** 找关卡 by id */
export function findLevel(levelId: string): {chapterId: string, chapterTitle: string, level: import("./types").Level} | null {
  return allLevels().find(x => x.level.id === levelId) || null;
}

/** 下一关 id（线性解锁） */
export function nextLevelId(levelId: string): string | null {
  const list = allLevels();
  const idx = list.findIndex(x => x.level.id === levelId);
  if (idx < 0 || idx >= list.length - 1) return null;
  return list[idx + 1].level.id;
}
